// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jennah/datastore/v1/data.proto

package datastore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_CommitData_FullMethodName = "/jennahapi.datastore.v1.DataService/CommitData"
	DataService_QueryData_FullMethodName  = "/jennahapi.datastore.v1.DataService/QueryData"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataService is the structured row transport for a dataset's application tables.
type DataServiceClient interface {
	// Applies a set of structured row operations across one or more of the
	// dataset's tables in a SINGLE read-write transaction, clamped to
	// `(EnterpriseId, DatasetId)`. All-or-nothing: if any operation fails, no
	// operation's rows are written.
	//
	// This is the atomic multi-table write a split stack cannot offer: a row, its
	// embedding, and rows in other tables land together or not at all. An
	// operation naming a table absent from the dataset's catalog rejects the whole
	// commit, writing nothing.
	//
	// An operation may also make its OWN effect a precondition of the commit (see
	// RowOperation.expect), which is what makes compare-and-set expressible. An
	// unmet precondition returns FAILED_PRECONDITION and writes nothing; the
	// status carries a google.rpc.PreconditionFailure naming the operation, its
	// table, and the expected and observed counts, so it is distinguishable from
	// a rejected truncation, which reports the same code. Never retry it blindly:
	// re-read the contended row and decide again.
	//
	// A commit whose response is LOST is recoverable only if it carried an
	// idempotency_key: resending it with the same key applies nothing a second
	// time and returns the original commit's receipt. Without a key there is no
	// way to ask whether a commit landed, and no way to say "this is the same one
	// I already sent". See CommitDataRequest.idempotency_key.
	//
	// Requires datastore.data:write and a dataset selector matching dataset_id.
	CommitData(ctx context.Context, in *CommitDataRequest, opts ...grpc.CallOption) (*CommitDataResponse, error)
	// Evaluates a multi-section read against ONE read snapshot, so a relational
	// predicate and a vector ranking observe the same instant: an optional
	// relational section and an optional exact-KNN vector section. Every section
	// is clamped to the caller's `(EnterpriseId, DatasetId)` slice, and joins are
	// restricted to tables within the same dataset.
	//
	// The request is a SECTIONED ENVELOPE for the same reason QueryMemory is: a
	// flat relational-shaped request would make adding a further modality a
	// breaking change to a published endpoint. A graph section is the intended
	// third.
	//
	// Requires datastore.data:read and a dataset selector matching dataset_id.
	QueryData(ctx context.Context, in *QueryDataRequest, opts ...grpc.CallOption) (*QueryDataResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) CommitData(ctx context.Context, in *CommitDataRequest, opts ...grpc.CallOption) (*CommitDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitDataResponse)
	err := c.cc.Invoke(ctx, DataService_CommitData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) QueryData(ctx context.Context, in *QueryDataRequest, opts ...grpc.CallOption) (*QueryDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDataResponse)
	err := c.cc.Invoke(ctx, DataService_QueryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
//
// DataService is the structured row transport for a dataset's application tables.
type DataServiceServer interface {
	// Applies a set of structured row operations across one or more of the
	// dataset's tables in a SINGLE read-write transaction, clamped to
	// `(EnterpriseId, DatasetId)`. All-or-nothing: if any operation fails, no
	// operation's rows are written.
	//
	// This is the atomic multi-table write a split stack cannot offer: a row, its
	// embedding, and rows in other tables land together or not at all. An
	// operation naming a table absent from the dataset's catalog rejects the whole
	// commit, writing nothing.
	//
	// An operation may also make its OWN effect a precondition of the commit (see
	// RowOperation.expect), which is what makes compare-and-set expressible. An
	// unmet precondition returns FAILED_PRECONDITION and writes nothing; the
	// status carries a google.rpc.PreconditionFailure naming the operation, its
	// table, and the expected and observed counts, so it is distinguishable from
	// a rejected truncation, which reports the same code. Never retry it blindly:
	// re-read the contended row and decide again.
	//
	// A commit whose response is LOST is recoverable only if it carried an
	// idempotency_key: resending it with the same key applies nothing a second
	// time and returns the original commit's receipt. Without a key there is no
	// way to ask whether a commit landed, and no way to say "this is the same one
	// I already sent". See CommitDataRequest.idempotency_key.
	//
	// Requires datastore.data:write and a dataset selector matching dataset_id.
	CommitData(context.Context, *CommitDataRequest) (*CommitDataResponse, error)
	// Evaluates a multi-section read against ONE read snapshot, so a relational
	// predicate and a vector ranking observe the same instant: an optional
	// relational section and an optional exact-KNN vector section. Every section
	// is clamped to the caller's `(EnterpriseId, DatasetId)` slice, and joins are
	// restricted to tables within the same dataset.
	//
	// The request is a SECTIONED ENVELOPE for the same reason QueryMemory is: a
	// flat relational-shaped request would make adding a further modality a
	// breaking change to a published endpoint. A graph section is the intended
	// third.
	//
	// Requires datastore.data:read and a dataset selector matching dataset_id.
	QueryData(context.Context, *QueryDataRequest) (*QueryDataResponse, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) CommitData(context.Context, *CommitDataRequest) (*CommitDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitData not implemented")
}
func (UnimplementedDataServiceServer) QueryData(context.Context, *QueryDataRequest) (*QueryDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryData not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_CommitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CommitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_CommitData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CommitData(ctx, req.(*CommitDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_QueryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).QueryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_QueryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).QueryData(ctx, req.(*QueryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jennahapi.datastore.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitData",
			Handler:    _DataService_CommitData_Handler,
		},
		{
			MethodName: "QueryData",
			Handler:    _DataService_QueryData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jennah/datastore/v1/data.proto",
}
