// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jennah/approval/v1/approval.proto

package approval

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApprovalService_CreateApproval_FullMethodName             = "/jennahapi.approval.v1.ApprovalService/CreateApproval"
	ApprovalService_GetApproval_FullMethodName                = "/jennahapi.approval.v1.ApprovalService/GetApproval"
	ApprovalService_ListApprovals_FullMethodName              = "/jennahapi.approval.v1.ApprovalService/ListApprovals"
	ApprovalService_CancelApproval_FullMethodName             = "/jennahapi.approval.v1.ApprovalService/CancelApproval"
	ApprovalService_WaitApproval_FullMethodName               = "/jennahapi.approval.v1.ApprovalService/WaitApproval"
	ApprovalService_ResendApprovalNotification_FullMethodName = "/jennahapi.approval.v1.ApprovalService/ResendApprovalNotification"
	ApprovalService_DescribeApprovalByToken_FullMethodName    = "/jennahapi.approval.v1.ApprovalService/DescribeApprovalByToken"
	ApprovalService_SubmitApprovalDecision_FullMethodName     = "/jennahapi.approval.v1.ApprovalService/SubmitApprovalDecision"
	ApprovalService_ListApprovers_FullMethodName              = "/jennahapi.approval.v1.ApprovalService/ListApprovers"
	ApprovalService_AddApprover_FullMethodName                = "/jennahapi.approval.v1.ApprovalService/AddApprover"
	ApprovalService_RemoveApprover_FullMethodName             = "/jennahapi.approval.v1.ApprovalService/RemoveApprover"
)

// ApprovalServiceClient is the client API for ApprovalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApprovalService puts a decision to a named human and records the answer.
type ApprovalServiceClient interface {
	// Creates an approval request under the caller's enterprise and attempts to
	// notify its approvers. External (gateway) RPC. Authenticated, and gated on
	// `approval.requests:create`; when `agent_id` is set the caller's credential
	// must additionally reach that agent under the agent-selector rules, so
	// approval authority cannot be used to route around agent reach.
	//
	// Success means the approval is DURABLY RECORDED. It does not mean anyone was
	// notified: delivery is attempted after commit and reported per approver on
	// read (see Approver.delivery_state). A creation whose mail could not be sent
	// is still a pending approval, not a failure.
	//
	// Idempotent on `request_key`: a replay with the same key and the same content
	// returns the existing approval with `already_existed` true, mints no second
	// token, and sends no second email. A replay reusing the key with DIFFERENT
	// content is ALREADY_EXISTS rather than a silent hand-back of the first
	// question's receipt.
	//
	// Refused in full (no approval row and no mail sent) when
	// any listed approver is unaddressable (see AddApprover for what makes an
	// address reachable), when `require_authenticated_decider` is set alongside a
	// non-member approver, when the approvers eligible to decide are fewer than
	// `required_approvals`, or when an entitlement ceiling is reached.
	CreateApproval(ctx context.Context, in *CreateApprovalRequest, opts ...grpc.CallOption) (*CreateApprovalResponse, error)
	// Reads one approval with its approvers, their delivery state, and its recorded
	// decisions. External (gateway) RPC. Authenticated. Readable by a holder of
	// `approval.requests:read`, and (with no permission at all) by a listed
	// approver reading what was addressed to them.
	//
	// Expiry is applied at READ: an approval past its deadline is reported terminal
	// whether or not a background pass has materialized that. An approval_id not
	// owned by the caller's enterprise is not found, disclosing nothing about its
	// existence, status, or approvers.
	GetApproval(ctx context.Context, in *GetApprovalRequest, opts ...grpc.CallOption) (*GetApprovalResponse, error)
	// Lists the caller enterprise's approvals, newest first, with
	// page_size/page_token pagination. External (gateway) RPC. Authenticated.
	//
	// What a caller sees depends on what they hold: with `approval.requests:read`,
	// the enterprise's approvals (minus any scoped to an agent outside their
	// reach); without it, only the approvals that list the caller as an approver.
	// `only_awaiting_me` narrows either case to the caller's own queue, which is
	// what the console's approvals inbox renders.
	ListApprovals(ctx context.Context, in *ListApprovalsRequest, opts ...grpc.CallOption) (*ListApprovalsResponse, error)
	// Withdraws a PENDING approval, making it terminally CANCELLED and rendering
	// every outstanding capability token unspendable. External (gateway) RPC.
	// Authenticated, gated on `approval.requests:cancel`.
	//
	// Cancelling an already-terminal approval is FAILED_PRECONDITION.
	CancelApproval(ctx context.Context, in *CancelApprovalRequest, opts ...grpc.CallOption) (*CancelApprovalResponse, error)
	// Blocks until the approval reaches a terminal status or the wait elapses, then
	// returns its current state. External (gateway) RPC. Authenticated, same read
	// authority as GetApproval.
	//
	// A bounded server-side poll, not a stream: the effective wait is clamped to a
	// platform maximum, and reaching that maximum returns the still-PENDING approval.
	// Safe to call repeatedly, and it holds no resource a caller must release.
	WaitApproval(ctx context.Context, in *WaitApprovalRequest, opts ...grpc.CallOption) (*WaitApprovalResponse, error)
	// Re-sends the notification for a still-PENDING approval. External (gateway)
	// RPC. Authenticated, gated on `approval.requests:create` (a resend sends mail,
	// so it is a create-class act, not a read).
	//
	// Mints an ADDITIONAL token rather than re-rendering the approver's existing
	// one. A resend therefore invalidates
	// nothing: the copy already in the approver's mailbox keeps working. Single
	// use is a property of the APPROVER, not of a token: whichever copy they act on
	// first records their one decision, and every other token outstanding for them
	// is then refused as already-decided. Resends count against the enterprise's
	// notification ceiling.
	ResendApprovalNotification(ctx context.Context, in *ResendApprovalNotificationRequest, opts ...grpc.CallOption) (*ResendApprovalNotificationResponse, error)
	// Renders one approval to the holder of an emailed capability token. External
	// (gateway) RPC. UNAUTHENTICATED in the bearer sense and on the interceptor's
	// unauthenticated allowlist; it authenticates its caller by resolving the
	// presented token to a live approver record, and refuses when it cannot.
	//
	// Read-only: nothing reachable by a fetch may record a decision or spend a token.
	// Calling this repeatedly is safe and changes nothing.
	//
	// The token is taken in the BODY. It appears in no path and no query string
	// anywhere in this service, because the emailed link carries it in the URL
	// FRAGMENT (which browsers do not send to servers) so it reaches the
	// approver's browser and neither the console's access log, a referrer header, a
	// link-rewriting proxy's telemetry, nor jennah's own logs.
	//
	// A token that is expired, spent, revoked, cancelled, or never issued is
	// refused with ONE indistinguishable message, so a caller cannot probe which
	// tokens exist.
	DescribeApprovalByToken(ctx context.Context, in *DescribeApprovalByTokenRequest, opts ...grpc.CallOption) (*DescribeApprovalByTokenResponse, error)
	// Records a decision, once. External (gateway) RPC. On the unauthenticated
	// allowlist for the token origin, and dynamically authorized in the handler for
	// both origins: the permission catalog deliberately has NO decide action,
	// because authority to decide is capability-based (holding the emailed token,
	// or being a listed approver) rather than something a role can grant.
	//
	// Exactly two origins are accepted:
	//
	//	(a) a valid unspent capability token, presented in the body; or
	//	(b) an authenticated human who is a listed approver on that approval.
	//
	// A KEY-authenticated caller is refused unconditionally, with or without a
	// valid token: an agent may raise a request but may never satisfy its own, and
	// a human decision may not be rendered by a service principal. An authenticated
	// human who is not a listed approver is refused too, enterprise admin or not.
	//
	// This is the explicit submission the read-only render is deliberately split
	// from: it carries the decision value. Terminal is terminal: a second submission, including one matching the
	// recorded outcome, is refused as already-decided rather than recorded twice.
	SubmitApprovalDecision(ctx context.Context, in *SubmitApprovalDecisionRequest, opts ...grpc.CallOption) (*SubmitApprovalDecisionResponse, error)
	// Lists the enterprise's approver allowlist entries. External (gateway) RPC.
	// Authenticated, gated on `approval.approvers:read`.
	ListApprovers(ctx context.Context, in *ListApproversRequest, opts ...grpc.CallOption) (*ListApproversResponse, error)
	// Adds an email address or a domain to the enterprise's approver allowlist.
	// External (gateway) RPC. Authenticated, gated on `approval.approvers:manage`,
	// which is management-class and therefore can never appear in an API key's
	// scope: a key-authenticated caller is refused outright.
	//
	// Members of the enterprise are ALWAYS addressable and need no entry here. The
	// allowlist exists only for non-members, and the refusal of key-authenticated
	// callers is the point of the whole mechanism: an agent must not be able to
	// widen the set of people the platform will mail on its behalf, or the platform
	// becomes an unbranded phishing and spam channel.
	AddApprover(ctx context.Context, in *AddApproverRequest, opts ...grpc.CallOption) (*AddApproverResponse, error)
	// Removes an allowlist entry. External (gateway) RPC. Authenticated, gated on
	// `approval.approvers:manage`; key-authenticated callers refused.
	//
	// Removal narrows future addressing only. Approvals already created keep their
	// approvers and their live tokens, because a person mid-decision is not made
	// undecidable by an administrative edit.
	RemoveApprover(ctx context.Context, in *RemoveApproverRequest, opts ...grpc.CallOption) (*RemoveApproverResponse, error)
}

type approvalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalServiceClient(cc grpc.ClientConnInterface) ApprovalServiceClient {
	return &approvalServiceClient{cc}
}

func (c *approvalServiceClient) CreateApproval(ctx context.Context, in *CreateApprovalRequest, opts ...grpc.CallOption) (*CreateApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApprovalResponse)
	err := c.cc.Invoke(ctx, ApprovalService_CreateApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetApproval(ctx context.Context, in *GetApprovalRequest, opts ...grpc.CallOption) (*GetApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApprovalResponse)
	err := c.cc.Invoke(ctx, ApprovalService_GetApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) ListApprovals(ctx context.Context, in *ListApprovalsRequest, opts ...grpc.CallOption) (*ListApprovalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApprovalsResponse)
	err := c.cc.Invoke(ctx, ApprovalService_ListApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) CancelApproval(ctx context.Context, in *CancelApprovalRequest, opts ...grpc.CallOption) (*CancelApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelApprovalResponse)
	err := c.cc.Invoke(ctx, ApprovalService_CancelApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) WaitApproval(ctx context.Context, in *WaitApprovalRequest, opts ...grpc.CallOption) (*WaitApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitApprovalResponse)
	err := c.cc.Invoke(ctx, ApprovalService_WaitApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) ResendApprovalNotification(ctx context.Context, in *ResendApprovalNotificationRequest, opts ...grpc.CallOption) (*ResendApprovalNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendApprovalNotificationResponse)
	err := c.cc.Invoke(ctx, ApprovalService_ResendApprovalNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) DescribeApprovalByToken(ctx context.Context, in *DescribeApprovalByTokenRequest, opts ...grpc.CallOption) (*DescribeApprovalByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeApprovalByTokenResponse)
	err := c.cc.Invoke(ctx, ApprovalService_DescribeApprovalByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) SubmitApprovalDecision(ctx context.Context, in *SubmitApprovalDecisionRequest, opts ...grpc.CallOption) (*SubmitApprovalDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitApprovalDecisionResponse)
	err := c.cc.Invoke(ctx, ApprovalService_SubmitApprovalDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) ListApprovers(ctx context.Context, in *ListApproversRequest, opts ...grpc.CallOption) (*ListApproversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApproversResponse)
	err := c.cc.Invoke(ctx, ApprovalService_ListApprovers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) AddApprover(ctx context.Context, in *AddApproverRequest, opts ...grpc.CallOption) (*AddApproverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddApproverResponse)
	err := c.cc.Invoke(ctx, ApprovalService_AddApprover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) RemoveApprover(ctx context.Context, in *RemoveApproverRequest, opts ...grpc.CallOption) (*RemoveApproverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveApproverResponse)
	err := c.cc.Invoke(ctx, ApprovalService_RemoveApprover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApprovalServiceServer is the server API for ApprovalService service.
// All implementations must embed UnimplementedApprovalServiceServer
// for forward compatibility.
//
// ApprovalService puts a decision to a named human and records the answer.
type ApprovalServiceServer interface {
	// Creates an approval request under the caller's enterprise and attempts to
	// notify its approvers. External (gateway) RPC. Authenticated, and gated on
	// `approval.requests:create`; when `agent_id` is set the caller's credential
	// must additionally reach that agent under the agent-selector rules, so
	// approval authority cannot be used to route around agent reach.
	//
	// Success means the approval is DURABLY RECORDED. It does not mean anyone was
	// notified: delivery is attempted after commit and reported per approver on
	// read (see Approver.delivery_state). A creation whose mail could not be sent
	// is still a pending approval, not a failure.
	//
	// Idempotent on `request_key`: a replay with the same key and the same content
	// returns the existing approval with `already_existed` true, mints no second
	// token, and sends no second email. A replay reusing the key with DIFFERENT
	// content is ALREADY_EXISTS rather than a silent hand-back of the first
	// question's receipt.
	//
	// Refused in full (no approval row and no mail sent) when
	// any listed approver is unaddressable (see AddApprover for what makes an
	// address reachable), when `require_authenticated_decider` is set alongside a
	// non-member approver, when the approvers eligible to decide are fewer than
	// `required_approvals`, or when an entitlement ceiling is reached.
	CreateApproval(context.Context, *CreateApprovalRequest) (*CreateApprovalResponse, error)
	// Reads one approval with its approvers, their delivery state, and its recorded
	// decisions. External (gateway) RPC. Authenticated. Readable by a holder of
	// `approval.requests:read`, and (with no permission at all) by a listed
	// approver reading what was addressed to them.
	//
	// Expiry is applied at READ: an approval past its deadline is reported terminal
	// whether or not a background pass has materialized that. An approval_id not
	// owned by the caller's enterprise is not found, disclosing nothing about its
	// existence, status, or approvers.
	GetApproval(context.Context, *GetApprovalRequest) (*GetApprovalResponse, error)
	// Lists the caller enterprise's approvals, newest first, with
	// page_size/page_token pagination. External (gateway) RPC. Authenticated.
	//
	// What a caller sees depends on what they hold: with `approval.requests:read`,
	// the enterprise's approvals (minus any scoped to an agent outside their
	// reach); without it, only the approvals that list the caller as an approver.
	// `only_awaiting_me` narrows either case to the caller's own queue, which is
	// what the console's approvals inbox renders.
	ListApprovals(context.Context, *ListApprovalsRequest) (*ListApprovalsResponse, error)
	// Withdraws a PENDING approval, making it terminally CANCELLED and rendering
	// every outstanding capability token unspendable. External (gateway) RPC.
	// Authenticated, gated on `approval.requests:cancel`.
	//
	// Cancelling an already-terminal approval is FAILED_PRECONDITION.
	CancelApproval(context.Context, *CancelApprovalRequest) (*CancelApprovalResponse, error)
	// Blocks until the approval reaches a terminal status or the wait elapses, then
	// returns its current state. External (gateway) RPC. Authenticated, same read
	// authority as GetApproval.
	//
	// A bounded server-side poll, not a stream: the effective wait is clamped to a
	// platform maximum, and reaching that maximum returns the still-PENDING approval.
	// Safe to call repeatedly, and it holds no resource a caller must release.
	WaitApproval(context.Context, *WaitApprovalRequest) (*WaitApprovalResponse, error)
	// Re-sends the notification for a still-PENDING approval. External (gateway)
	// RPC. Authenticated, gated on `approval.requests:create` (a resend sends mail,
	// so it is a create-class act, not a read).
	//
	// Mints an ADDITIONAL token rather than re-rendering the approver's existing
	// one. A resend therefore invalidates
	// nothing: the copy already in the approver's mailbox keeps working. Single
	// use is a property of the APPROVER, not of a token: whichever copy they act on
	// first records their one decision, and every other token outstanding for them
	// is then refused as already-decided. Resends count against the enterprise's
	// notification ceiling.
	ResendApprovalNotification(context.Context, *ResendApprovalNotificationRequest) (*ResendApprovalNotificationResponse, error)
	// Renders one approval to the holder of an emailed capability token. External
	// (gateway) RPC. UNAUTHENTICATED in the bearer sense and on the interceptor's
	// unauthenticated allowlist; it authenticates its caller by resolving the
	// presented token to a live approver record, and refuses when it cannot.
	//
	// Read-only: nothing reachable by a fetch may record a decision or spend a token.
	// Calling this repeatedly is safe and changes nothing.
	//
	// The token is taken in the BODY. It appears in no path and no query string
	// anywhere in this service, because the emailed link carries it in the URL
	// FRAGMENT (which browsers do not send to servers) so it reaches the
	// approver's browser and neither the console's access log, a referrer header, a
	// link-rewriting proxy's telemetry, nor jennah's own logs.
	//
	// A token that is expired, spent, revoked, cancelled, or never issued is
	// refused with ONE indistinguishable message, so a caller cannot probe which
	// tokens exist.
	DescribeApprovalByToken(context.Context, *DescribeApprovalByTokenRequest) (*DescribeApprovalByTokenResponse, error)
	// Records a decision, once. External (gateway) RPC. On the unauthenticated
	// allowlist for the token origin, and dynamically authorized in the handler for
	// both origins: the permission catalog deliberately has NO decide action,
	// because authority to decide is capability-based (holding the emailed token,
	// or being a listed approver) rather than something a role can grant.
	//
	// Exactly two origins are accepted:
	//
	//	(a) a valid unspent capability token, presented in the body; or
	//	(b) an authenticated human who is a listed approver on that approval.
	//
	// A KEY-authenticated caller is refused unconditionally, with or without a
	// valid token: an agent may raise a request but may never satisfy its own, and
	// a human decision may not be rendered by a service principal. An authenticated
	// human who is not a listed approver is refused too, enterprise admin or not.
	//
	// This is the explicit submission the read-only render is deliberately split
	// from: it carries the decision value. Terminal is terminal: a second submission, including one matching the
	// recorded outcome, is refused as already-decided rather than recorded twice.
	SubmitApprovalDecision(context.Context, *SubmitApprovalDecisionRequest) (*SubmitApprovalDecisionResponse, error)
	// Lists the enterprise's approver allowlist entries. External (gateway) RPC.
	// Authenticated, gated on `approval.approvers:read`.
	ListApprovers(context.Context, *ListApproversRequest) (*ListApproversResponse, error)
	// Adds an email address or a domain to the enterprise's approver allowlist.
	// External (gateway) RPC. Authenticated, gated on `approval.approvers:manage`,
	// which is management-class and therefore can never appear in an API key's
	// scope: a key-authenticated caller is refused outright.
	//
	// Members of the enterprise are ALWAYS addressable and need no entry here. The
	// allowlist exists only for non-members, and the refusal of key-authenticated
	// callers is the point of the whole mechanism: an agent must not be able to
	// widen the set of people the platform will mail on its behalf, or the platform
	// becomes an unbranded phishing and spam channel.
	AddApprover(context.Context, *AddApproverRequest) (*AddApproverResponse, error)
	// Removes an allowlist entry. External (gateway) RPC. Authenticated, gated on
	// `approval.approvers:manage`; key-authenticated callers refused.
	//
	// Removal narrows future addressing only. Approvals already created keep their
	// approvers and their live tokens, because a person mid-decision is not made
	// undecidable by an administrative edit.
	RemoveApprover(context.Context, *RemoveApproverRequest) (*RemoveApproverResponse, error)
	mustEmbedUnimplementedApprovalServiceServer()
}

// UnimplementedApprovalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApprovalServiceServer struct{}

func (UnimplementedApprovalServiceServer) CreateApproval(context.Context, *CreateApprovalRequest) (*CreateApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApproval not implemented")
}
func (UnimplementedApprovalServiceServer) GetApproval(context.Context, *GetApprovalRequest) (*GetApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApproval not implemented")
}
func (UnimplementedApprovalServiceServer) ListApprovals(context.Context, *ListApprovalsRequest) (*ListApprovalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApprovals not implemented")
}
func (UnimplementedApprovalServiceServer) CancelApproval(context.Context, *CancelApprovalRequest) (*CancelApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelApproval not implemented")
}
func (UnimplementedApprovalServiceServer) WaitApproval(context.Context, *WaitApprovalRequest) (*WaitApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitApproval not implemented")
}
func (UnimplementedApprovalServiceServer) ResendApprovalNotification(context.Context, *ResendApprovalNotificationRequest) (*ResendApprovalNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResendApprovalNotification not implemented")
}
func (UnimplementedApprovalServiceServer) DescribeApprovalByToken(context.Context, *DescribeApprovalByTokenRequest) (*DescribeApprovalByTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeApprovalByToken not implemented")
}
func (UnimplementedApprovalServiceServer) SubmitApprovalDecision(context.Context, *SubmitApprovalDecisionRequest) (*SubmitApprovalDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitApprovalDecision not implemented")
}
func (UnimplementedApprovalServiceServer) ListApprovers(context.Context, *ListApproversRequest) (*ListApproversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApprovers not implemented")
}
func (UnimplementedApprovalServiceServer) AddApprover(context.Context, *AddApproverRequest) (*AddApproverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddApprover not implemented")
}
func (UnimplementedApprovalServiceServer) RemoveApprover(context.Context, *RemoveApproverRequest) (*RemoveApproverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveApprover not implemented")
}
func (UnimplementedApprovalServiceServer) mustEmbedUnimplementedApprovalServiceServer() {}
func (UnimplementedApprovalServiceServer) testEmbeddedByValue()                         {}

// UnsafeApprovalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalServiceServer will
// result in compilation errors.
type UnsafeApprovalServiceServer interface {
	mustEmbedUnimplementedApprovalServiceServer()
}

func RegisterApprovalServiceServer(s grpc.ServiceRegistrar, srv ApprovalServiceServer) {
	// If the following call panics, it indicates UnimplementedApprovalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApprovalService_ServiceDesc, srv)
}

func _ApprovalService_CreateApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).CreateApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_CreateApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).CreateApproval(ctx, req.(*CreateApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetApproval(ctx, req.(*GetApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_ListApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).ListApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_ListApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).ListApprovals(ctx, req.(*ListApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_CancelApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).CancelApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_CancelApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).CancelApproval(ctx, req.(*CancelApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_WaitApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).WaitApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_WaitApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).WaitApproval(ctx, req.(*WaitApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_ResendApprovalNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendApprovalNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).ResendApprovalNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_ResendApprovalNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).ResendApprovalNotification(ctx, req.(*ResendApprovalNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_DescribeApprovalByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeApprovalByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).DescribeApprovalByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_DescribeApprovalByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).DescribeApprovalByToken(ctx, req.(*DescribeApprovalByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_SubmitApprovalDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitApprovalDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).SubmitApprovalDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_SubmitApprovalDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).SubmitApprovalDecision(ctx, req.(*SubmitApprovalDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_ListApprovers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApproversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).ListApprovers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_ListApprovers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).ListApprovers(ctx, req.(*ListApproversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_AddApprover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApproverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).AddApprover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_AddApprover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).AddApprover(ctx, req.(*AddApproverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_RemoveApprover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveApproverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).RemoveApprover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_RemoveApprover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).RemoveApprover(ctx, req.(*RemoveApproverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApprovalService_ServiceDesc is the grpc.ServiceDesc for ApprovalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApprovalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jennahapi.approval.v1.ApprovalService",
	HandlerType: (*ApprovalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApproval",
			Handler:    _ApprovalService_CreateApproval_Handler,
		},
		{
			MethodName: "GetApproval",
			Handler:    _ApprovalService_GetApproval_Handler,
		},
		{
			MethodName: "ListApprovals",
			Handler:    _ApprovalService_ListApprovals_Handler,
		},
		{
			MethodName: "CancelApproval",
			Handler:    _ApprovalService_CancelApproval_Handler,
		},
		{
			MethodName: "WaitApproval",
			Handler:    _ApprovalService_WaitApproval_Handler,
		},
		{
			MethodName: "ResendApprovalNotification",
			Handler:    _ApprovalService_ResendApprovalNotification_Handler,
		},
		{
			MethodName: "DescribeApprovalByToken",
			Handler:    _ApprovalService_DescribeApprovalByToken_Handler,
		},
		{
			MethodName: "SubmitApprovalDecision",
			Handler:    _ApprovalService_SubmitApprovalDecision_Handler,
		},
		{
			MethodName: "ListApprovers",
			Handler:    _ApprovalService_ListApprovers_Handler,
		},
		{
			MethodName: "AddApprover",
			Handler:    _ApprovalService_AddApprover_Handler,
		},
		{
			MethodName: "RemoveApprover",
			Handler:    _ApprovalService_RemoveApprover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jennah/approval/v1/approval.proto",
}
