// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jennah/platform/v1/platform.proto

package platform

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformService_ListLocations_FullMethodName = "/jennahapi.platform.v1.PlatformService/ListLocations"
)

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlatformService exposes facts about the platform itself rather than about any
// enterprise's resources: topology that is operator-owned and identical for every
// caller.
//
// It exists because location discovery outgrew AgentService. The listing began as
// ListRegions there, when agent workspaces were the only thing that had a
// placement. The application datastore gave locations a second consumer, and a
// listing describing where DATASETS may live does not belong on the service that
// manages agents — a caller holding only datastore permissions would have to ask
// the agent surface where its data can go.
type PlatformServiceClient interface {
	// Lists the locations tenant resources may be placed in, and what each one is
	// provisioned for. Callers cannot know the valid location values without
	// asking: the set is an operator-defined allowlist, not a pattern they can
	// construct.
	//
	// Available to any authenticated caller and requires no permission: the set is
	// non-sensitive operator topology, identical for every enterprise, and a
	// pre-flight region picker needs it before any resource exists to be authorized
	// against.
	//
	// Replaces AgentService.ListRegions, which was removed rather than deprecated.
	ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLocationsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations must embed UnimplementedPlatformServiceServer
// for forward compatibility.
//
// PlatformService exposes facts about the platform itself rather than about any
// enterprise's resources: topology that is operator-owned and identical for every
// caller.
//
// It exists because location discovery outgrew AgentService. The listing began as
// ListRegions there, when agent workspaces were the only thing that had a
// placement. The application datastore gave locations a second consumer, and a
// listing describing where DATASETS may live does not belong on the service that
// manages agents — a caller holding only datastore permissions would have to ask
// the agent surface where its data can go.
type PlatformServiceServer interface {
	// Lists the locations tenant resources may be placed in, and what each one is
	// provisioned for. Callers cannot know the valid location values without
	// asking: the set is an operator-defined allowlist, not a pattern they can
	// construct.
	//
	// Available to any authenticated caller and requires no permission: the set is
	// non-sensitive operator topology, identical for every enterprise, and a
	// pre-flight region picker needs it before any resource exists to be authorized
	// against.
	//
	// Replaces AgentService.ListRegions, which was removed rather than deprecated.
	ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error)
	mustEmbedUnimplementedPlatformServiceServer()
}

// UnimplementedPlatformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServiceServer struct{}

func (UnimplementedPlatformServiceServer) ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLocations not implemented")
}
func (UnimplementedPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {}
func (UnimplementedPlatformServiceServer) testEmbeddedByValue()                         {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	// If the following call panics, it indicates UnimplementedPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_ListLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListLocations(ctx, req.(*ListLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jennahapi.platform.v1.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLocations",
			Handler:    _PlatformService_ListLocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jennah/platform/v1/platform.proto",
}
