// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jennah/platform/v1/platform.proto

package platform

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The kind of placement a location names.
//
// This is surfaced because the choice is permanent and the trade is real: a
// tenant picking where a dataset lives is choosing between write latency and
// globally consistent reads, and cannot make that choice from an opaque
// identifier. A client rendering a location picker uses this to say what each
// option actually costs.
type Geography int32

const (
	Geography_GEOGRAPHY_UNSPECIFIED Geography = 0
	// One cloud region. Lowest write latency; reads outside the region pay the
	// round trip.
	Geography_GEOGRAPHY_SINGLE_REGION Geography = 1
	// Several regions within a continent. Strongly consistent low-latency reads
	// across them, at the cost of write latency.
	Geography_GEOGRAPHY_MULTI_REGION Geography = 2
	// Multiple continents. The widest read geography and the highest write cost.
	Geography_GEOGRAPHY_GLOBAL Geography = 3
)

// Enum value maps for Geography.
var (
	Geography_name = map[int32]string{
		0: "GEOGRAPHY_UNSPECIFIED",
		1: "GEOGRAPHY_SINGLE_REGION",
		2: "GEOGRAPHY_MULTI_REGION",
		3: "GEOGRAPHY_GLOBAL",
	}
	Geography_value = map[string]int32{
		"GEOGRAPHY_UNSPECIFIED":   0,
		"GEOGRAPHY_SINGLE_REGION": 1,
		"GEOGRAPHY_MULTI_REGION":  2,
		"GEOGRAPHY_GLOBAL":        3,
	}
)

func (x Geography) Enum() *Geography {
	p := new(Geography)
	*p = x
	return p
}

func (x Geography) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Geography) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_platform_v1_platform_proto_enumTypes[0].Descriptor()
}

func (Geography) Type() protoreflect.EnumType {
	return &file_jennah_platform_v1_platform_proto_enumTypes[0]
}

func (x Geography) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Geography.Descriptor instead.
func (Geography) EnumDescriptor() ([]byte, []int) {
	return file_jennah_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

// A location tenant resources may be placed in.
//
// A location is a placement identifier and NOT necessarily a single cloud region:
// it may name a multi-region or global placement (see Geography). That is why a
// location id is validated by allowlist membership only and never against a
// region-shaped pattern, and why the ids are Jennah's own rather than a cloud
// vendor's: the backing topology can change without breaking the API.
type Location struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // e.g. "us-central-1", "nam3"
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // free-form and human-readable, e.g. "Tokyo, Japan"
	Geography   Geography              `protobuf:"varint,3,opt,name=geography,proto3,enum=jennahapi.platform.v1.Geography" json:"geography,omitempty"`
	// What this location is provisioned for. A surface's support block is PRESENT
	// when the location serves that surface and ABSENT when it does not, so there
	// is no way to express a contradiction like "supported, with no parameters".
	//
	// A location may serve one surface, both, or (transiently, mid-rollout) neither.
	// Each surface carries its own default flag because the defaults are configured
	// independently and need not name the same location.
	//
	// Adding a surface later means adding a field here; it does not change the
	// meaning of the ones already present.
	Agents        *AgentSupport   `protobuf:"bytes,4,opt,name=agents,proto3" json:"agents,omitempty"`
	Datasets      *DatasetSupport `protobuf:"bytes,5,opt,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_jennah_platform_v1_platform_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Location) GetGeography() Geography {
	if x != nil {
		return x.Geography
	}
	return Geography_GEOGRAPHY_UNSPECIFIED
}

func (x *Location) GetAgents() *AgentSupport {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *Location) GetDatasets() *DatasetSupport {
	if x != nil {
		return x.Datasets
	}
	return nil
}

// Agent-workspace support at a location.
type AgentSupport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true for the location CreateAgent uses when `region` is omitted.
	IsDefault     bool `protobuf:"varint,1,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSupport) Reset() {
	*x = AgentSupport{}
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSupport) ProtoMessage() {}

func (x *AgentSupport) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSupport.ProtoReflect.Descriptor instead.
func (*AgentSupport) Descriptor() ([]byte, []int) {
	return file_jennah_platform_v1_platform_proto_rawDescGZIP(), []int{1}
}

func (x *AgentSupport) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

// Application-datastore support at a location.
type DatasetSupport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true for the location CreateDataset uses when `location` is omitted.
	IsDefault bool `protobuf:"varint,1,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	// Output width of the embedding model registered here, or 0 when none is.
	//
	// It governs MANAGED vector columns only: the ones that name a source_column
	// and have their vector generated server-side. A managed column's declared
	// width must EQUAL this value, because an inline generated write whose output
	// does not fit the column is rejected outright, so a mismatched declaration
	// produces a table that accepts no managed write at all.
	//
	// 0 means no model is registered here and a managed column is refused at
	// declare time rather than accepted and left to fail on every row. It does NOT
	// mean vectors are unavailable: a caller-supplied vector column still works at
	// this location, and is deliberately unconstrained in width, since the platform
	// generates nothing for it and must not impose its own model on a path it does
	// not participate in.
	EmbeddingDimensions int32 `protobuf:"varint,2,opt,name=embedding_dimensions,json=embeddingDimensions,proto3" json:"embedding_dimensions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DatasetSupport) Reset() {
	*x = DatasetSupport{}
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetSupport) ProtoMessage() {}

func (x *DatasetSupport) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetSupport.ProtoReflect.Descriptor instead.
func (*DatasetSupport) Descriptor() ([]byte, []int) {
	return file_jennah_platform_v1_platform_proto_rawDescGZIP(), []int{2}
}

func (x *DatasetSupport) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *DatasetSupport) GetEmbeddingDimensions() int32 {
	if x != nil {
		return x.EmbeddingDimensions
	}
	return 0
}

// Request message for the PlatformService.ListLocations rpc. No parameters: the
// location set is global, not tenant- or page-scoped.
type ListLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsRequest) Reset() {
	*x = ListLocationsRequest{}
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsRequest) ProtoMessage() {}

func (x *ListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_jennah_platform_v1_platform_proto_rawDescGZIP(), []int{3}
}

// Response message for the PlatformService.ListLocations rpc.
type ListLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"` // ordered by id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsResponse) Reset() {
	*x = ListLocationsResponse{}
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResponse) ProtoMessage() {}

func (x *ListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_platform_v1_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_jennah_platform_v1_platform_proto_rawDescGZIP(), []int{4}
}

func (x *ListLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_jennah_platform_v1_platform_proto protoreflect.FileDescriptor

const file_jennah_platform_v1_platform_proto_rawDesc = "" +
	"\n" +
	"!jennah/platform/v1/platform.proto\x12\x15jennahapi.platform.v1\x1a\x1cgoogle/api/annotations.proto\"\xfc\x01\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12>\n" +
	"\tgeography\x18\x03 \x01(\x0e2 .jennahapi.platform.v1.GeographyR\tgeography\x12;\n" +
	"\x06agents\x18\x04 \x01(\v2#.jennahapi.platform.v1.AgentSupportR\x06agents\x12A\n" +
	"\bdatasets\x18\x05 \x01(\v2%.jennahapi.platform.v1.DatasetSupportR\bdatasets\"-\n" +
	"\fAgentSupport\x12\x1d\n" +
	"\n" +
	"is_default\x18\x01 \x01(\bR\tisDefault\"b\n" +
	"\x0eDatasetSupport\x12\x1d\n" +
	"\n" +
	"is_default\x18\x01 \x01(\bR\tisDefault\x121\n" +
	"\x14embedding_dimensions\x18\x02 \x01(\x05R\x13embeddingDimensions\"\x16\n" +
	"\x14ListLocationsRequest\"V\n" +
	"\x15ListLocationsResponse\x12=\n" +
	"\tlocations\x18\x01 \x03(\v2\x1f.jennahapi.platform.v1.LocationR\tlocations*u\n" +
	"\tGeography\x12\x19\n" +
	"\x15GEOGRAPHY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GEOGRAPHY_SINGLE_REGION\x10\x01\x12\x1a\n" +
	"\x16GEOGRAPHY_MULTI_REGION\x10\x02\x12\x14\n" +
	"\x10GEOGRAPHY_GLOBAL\x10\x032\x95\x01\n" +
	"\x0fPlatformService\x12\x81\x01\n" +
	"\rListLocations\x12+.jennahapi.platform.v1.ListLocationsRequest\x1a,.jennahapi.platform.v1.ListLocationsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/locationsB,Z*github.com/alphauslabs/jennah-api/platformb\x06proto3"

var (
	file_jennah_platform_v1_platform_proto_rawDescOnce sync.Once
	file_jennah_platform_v1_platform_proto_rawDescData []byte
)

func file_jennah_platform_v1_platform_proto_rawDescGZIP() []byte {
	file_jennah_platform_v1_platform_proto_rawDescOnce.Do(func() {
		file_jennah_platform_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jennah_platform_v1_platform_proto_rawDesc), len(file_jennah_platform_v1_platform_proto_rawDesc)))
	})
	return file_jennah_platform_v1_platform_proto_rawDescData
}

var file_jennah_platform_v1_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jennah_platform_v1_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jennah_platform_v1_platform_proto_goTypes = []any{
	(Geography)(0),                // 0: jennahapi.platform.v1.Geography
	(*Location)(nil),              // 1: jennahapi.platform.v1.Location
	(*AgentSupport)(nil),          // 2: jennahapi.platform.v1.AgentSupport
	(*DatasetSupport)(nil),        // 3: jennahapi.platform.v1.DatasetSupport
	(*ListLocationsRequest)(nil),  // 4: jennahapi.platform.v1.ListLocationsRequest
	(*ListLocationsResponse)(nil), // 5: jennahapi.platform.v1.ListLocationsResponse
}
var file_jennah_platform_v1_platform_proto_depIdxs = []int32{
	0, // 0: jennahapi.platform.v1.Location.geography:type_name -> jennahapi.platform.v1.Geography
	2, // 1: jennahapi.platform.v1.Location.agents:type_name -> jennahapi.platform.v1.AgentSupport
	3, // 2: jennahapi.platform.v1.Location.datasets:type_name -> jennahapi.platform.v1.DatasetSupport
	1, // 3: jennahapi.platform.v1.ListLocationsResponse.locations:type_name -> jennahapi.platform.v1.Location
	4, // 4: jennahapi.platform.v1.PlatformService.ListLocations:input_type -> jennahapi.platform.v1.ListLocationsRequest
	5, // 5: jennahapi.platform.v1.PlatformService.ListLocations:output_type -> jennahapi.platform.v1.ListLocationsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jennah_platform_v1_platform_proto_init() }
func file_jennah_platform_v1_platform_proto_init() {
	if File_jennah_platform_v1_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jennah_platform_v1_platform_proto_rawDesc), len(file_jennah_platform_v1_platform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jennah_platform_v1_platform_proto_goTypes,
		DependencyIndexes: file_jennah_platform_v1_platform_proto_depIdxs,
		EnumInfos:         file_jennah_platform_v1_platform_proto_enumTypes,
		MessageInfos:      file_jennah_platform_v1_platform_proto_msgTypes,
	}.Build()
	File_jennah_platform_v1_platform_proto = out.File
	file_jennah_platform_v1_platform_proto_goTypes = nil
	file_jennah_platform_v1_platform_proto_depIdxs = nil
}
