// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jennah/agent/v1/agent.proto

package agent

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle state of an agent workspace.
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	// Ready for use: the region and enterprise schema are provisioned and the
	// AgentInstances row exists in the data plane.
	AgentStatus_AGENT_STATUS_ACTIVE    AgentStatus = 1
	AgentStatus_AGENT_STATUS_PAUSED    AgentStatus = 2
	AgentStatus_AGENT_STATUS_COMPLETED AgentStatus = 3
	// Provisioning is still in flight (region instance and/or enterprise schema
	// being created). No data-plane row exists yet; poll GetAgent until ACTIVE.
	AgentStatus_AGENT_STATUS_PROVISIONING AgentStatus = 4
	// Provisioning failed; status_detail carries the reason. The caller may retry
	// SpawnAgent (idempotent on agent_instance_id) or destroy the failed record.
	AgentStatus_AGENT_STATUS_FAILED AgentStatus = 5
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_ACTIVE",
		2: "AGENT_STATUS_PAUSED",
		3: "AGENT_STATUS_COMPLETED",
		4: "AGENT_STATUS_PROVISIONING",
		5: "AGENT_STATUS_FAILED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED":  0,
		"AGENT_STATUS_ACTIVE":       1,
		"AGENT_STATUS_PAUSED":       2,
		"AGENT_STATUS_COMPLETED":    3,
		"AGENT_STATUS_PROVISIONING": 4,
		"AGENT_STATUS_FAILED":       5,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_jennah_agent_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// A single agent workspace: an isolated context bucket owned by exactly one
// enterprise and pinned to one home region for its lifetime.
type AgentInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enterprise that owns this agent, resolved from the caller's token. Echoed
	// for clarity; it is never accepted from a request body.
	EnterpriseId    string                 `protobuf:"bytes,1,opt,name=enterprise_id,json=enterpriseId,proto3" json:"enterprise_id,omitempty"`
	AgentInstanceId string                 `protobuf:"bytes,2,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"` // unique within the enterprise
	AgentName       string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Region          string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"` // Jennah region id, e.g. "us-east-1"
	Status          AgentStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=jennahapi.agent.v1.AgentStatus" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // server-assigned commit timestamp
	// Human-readable detail for a non-terminal/failed status (e.g. the region
	// provisioning phase, or the failure reason when status is FAILED). Empty for
	// a plain ACTIVE agent.
	StatusDetail  string `protobuf:"bytes,7,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInstance) Reset() {
	*x = AgentInstance{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInstance) ProtoMessage() {}

func (x *AgentInstance) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInstance.ProtoReflect.Descriptor instead.
func (*AgentInstance) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInstance) GetEnterpriseId() string {
	if x != nil {
		return x.EnterpriseId
	}
	return ""
}

func (x *AgentInstance) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *AgentInstance) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentInstance) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentInstance) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *AgentInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentInstance) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

// Request message for the AgentService.SpawnAgent rpc.
type SpawnAgentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentInstanceId string                 `protobuf:"bytes,1,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"` // caller-chosen id, unique within the enterprise
	AgentName       string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	// Optional Jennah region identifier (e.g. "us-east-1"). Must be in the
	// configured region allowlist; when empty the platform default region is used.
	Region        string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAgentRequest) Reset() {
	*x = SpawnAgentRequest{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentRequest) ProtoMessage() {}

func (x *SpawnAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentRequest.ProtoReflect.Descriptor instead.
func (*SpawnAgentRequest) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SpawnAgentRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *SpawnAgentRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *SpawnAgentRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// Response message for the AgentService.SpawnAgent rpc.
type SpawnAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInstance         `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAgentResponse) Reset() {
	*x = SpawnAgentResponse{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentResponse) ProtoMessage() {}

func (x *SpawnAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentResponse.ProtoReflect.Descriptor instead.
func (*SpawnAgentResponse) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SpawnAgentResponse) GetAgent() *AgentInstance {
	if x != nil {
		return x.Agent
	}
	return nil
}

// Request message for the AgentService.GetAgent rpc.
type GetAgentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentInstanceId string                 `protobuf:"bytes,1,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"` // path parameter
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

// Response message for the AgentService.GetAgent rpc.
type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInstance         `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentResponse) GetAgent() *AgentInstance {
	if x != nil {
		return x.Agent
	}
	return nil
}

// Request message for the AgentService.ListAgents rpc.
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // max agents to return; server picks a default when 0
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // next_page_token from a prior response; empty for the first page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response message for the AgentService.ListAgents rpc.
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInstance       `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty when there are no more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInstance {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request message for the AgentService.DestroyAgent rpc.
type DestroyAgentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentInstanceId string                 `protobuf:"bytes,1,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"` // path parameter
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DestroyAgentRequest) Reset() {
	*x = DestroyAgentRequest{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAgentRequest) ProtoMessage() {}

func (x *DestroyAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAgentRequest.ProtoReflect.Descriptor instead.
func (*DestroyAgentRequest) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyAgentRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

// Response message for the AgentService.DestroyAgent rpc.
//
// The erasure receipt: a commit timestamp plus how many rows were removed per
// memory type, so a caller can evidence a complete, atomic erasure.
type DestroyAgentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // cascade-delete commit timestamp
	ExecutionLogRows int64                  `protobuf:"varint,2,opt,name=execution_log_rows,json=executionLogRows,proto3" json:"execution_log_rows,omitempty"`
	VectorRows       int64                  `protobuf:"varint,3,opt,name=vector_rows,json=vectorRows,proto3" json:"vector_rows,omitempty"`
	GraphNodeRows    int64                  `protobuf:"varint,4,opt,name=graph_node_rows,json=graphNodeRows,proto3" json:"graph_node_rows,omitempty"`
	GraphEdgeRows    int64                  `protobuf:"varint,5,opt,name=graph_edge_rows,json=graphEdgeRows,proto3" json:"graph_edge_rows,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DestroyAgentResponse) Reset() {
	*x = DestroyAgentResponse{}
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAgentResponse) ProtoMessage() {}

func (x *DestroyAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAgentResponse.ProtoReflect.Descriptor instead.
func (*DestroyAgentResponse) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyAgentResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *DestroyAgentResponse) GetExecutionLogRows() int64 {
	if x != nil {
		return x.ExecutionLogRows
	}
	return 0
}

func (x *DestroyAgentResponse) GetVectorRows() int64 {
	if x != nil {
		return x.VectorRows
	}
	return 0
}

func (x *DestroyAgentResponse) GetGraphNodeRows() int64 {
	if x != nil {
		return x.GraphNodeRows
	}
	return 0
}

func (x *DestroyAgentResponse) GetGraphEdgeRows() int64 {
	if x != nil {
		return x.GraphEdgeRows
	}
	return 0
}

var File_jennah_agent_v1_agent_proto protoreflect.FileDescriptor

const file_jennah_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bjennah/agent/v1/agent.proto\x12\x12jennahapi.agent.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n" +
	"\rAgentInstance\x12#\n" +
	"\renterprise_id\x18\x01 \x01(\tR\fenterpriseId\x12*\n" +
	"\x11agent_instance_id\x18\x02 \x01(\tR\x0fagentInstanceId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.jennahapi.agent.v1.AgentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\rstatus_detail\x18\a \x01(\tR\fstatusDetail\"v\n" +
	"\x11SpawnAgentRequest\x12*\n" +
	"\x11agent_instance_id\x18\x01 \x01(\tR\x0fagentInstanceId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"M\n" +
	"\x12SpawnAgentResponse\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.jennahapi.agent.v1.AgentInstanceR\x05agent\"=\n" +
	"\x0fGetAgentRequest\x12*\n" +
	"\x11agent_instance_id\x18\x01 \x01(\tR\x0fagentInstanceId\"K\n" +
	"\x10GetAgentResponse\x127\n" +
	"\x05agent\x18\x01 \x01(\v2!.jennahapi.agent.v1.AgentInstanceR\x05agent\"O\n" +
	"\x11ListAgentsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"w\n" +
	"\x12ListAgentsResponse\x129\n" +
	"\x06agents\x18\x01 \x03(\v2!.jennahapi.agent.v1.AgentInstanceR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"A\n" +
	"\x13DestroyAgentRequest\x12*\n" +
	"\x11agent_instance_id\x18\x01 \x01(\tR\x0fagentInstanceId\"\xf0\x01\n" +
	"\x14DestroyAgentResponse\x129\n" +
	"\n" +
	"deleted_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12,\n" +
	"\x12execution_log_rows\x18\x02 \x01(\x03R\x10executionLogRows\x12\x1f\n" +
	"\vvector_rows\x18\x03 \x01(\x03R\n" +
	"vectorRows\x12&\n" +
	"\x0fgraph_node_rows\x18\x04 \x01(\x03R\rgraphNodeRows\x12&\n" +
	"\x0fgraph_edge_rows\x18\x05 \x01(\x03R\rgraphEdgeRows*\xb1\x01\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AGENT_STATUS_ACTIVE\x10\x01\x12\x17\n" +
	"\x13AGENT_STATUS_PAUSED\x10\x02\x12\x1a\n" +
	"\x16AGENT_STATUS_COMPLETED\x10\x03\x12\x1d\n" +
	"\x19AGENT_STATUS_PROVISIONING\x10\x04\x12\x17\n" +
	"\x13AGENT_STATUS_FAILED\x10\x052\xfe\x03\n" +
	"\fAgentService\x12r\n" +
	"\n" +
	"SpawnAgent\x12%.jennahapi.agent.v1.SpawnAgentRequest\x1a&.jennahapi.agent.v1.SpawnAgentResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/agents\x12}\n" +
	"\bGetAgent\x12#.jennahapi.agent.v1.GetAgentRequest\x1a$.jennahapi.agent.v1.GetAgentResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/agents/{agent_instance_id}\x12o\n" +
	"\n" +
	"ListAgents\x12%.jennahapi.agent.v1.ListAgentsRequest\x1a&.jennahapi.agent.v1.ListAgentsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/agents\x12\x89\x01\n" +
	"\fDestroyAgent\x12'.jennahapi.agent.v1.DestroyAgentRequest\x1a(.jennahapi.agent.v1.DestroyAgentResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/v1/agents/{agent_instance_id}B)Z'github.com/alphauslabs/jennah-api/agentb\x06proto3"

var (
	file_jennah_agent_v1_agent_proto_rawDescOnce sync.Once
	file_jennah_agent_v1_agent_proto_rawDescData []byte
)

func file_jennah_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_jennah_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_jennah_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jennah_agent_v1_agent_proto_rawDesc), len(file_jennah_agent_v1_agent_proto_rawDesc)))
	})
	return file_jennah_agent_v1_agent_proto_rawDescData
}

var file_jennah_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jennah_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_jennah_agent_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),              // 0: jennahapi.agent.v1.AgentStatus
	(*AgentInstance)(nil),         // 1: jennahapi.agent.v1.AgentInstance
	(*SpawnAgentRequest)(nil),     // 2: jennahapi.agent.v1.SpawnAgentRequest
	(*SpawnAgentResponse)(nil),    // 3: jennahapi.agent.v1.SpawnAgentResponse
	(*GetAgentRequest)(nil),       // 4: jennahapi.agent.v1.GetAgentRequest
	(*GetAgentResponse)(nil),      // 5: jennahapi.agent.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),     // 6: jennahapi.agent.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 7: jennahapi.agent.v1.ListAgentsResponse
	(*DestroyAgentRequest)(nil),   // 8: jennahapi.agent.v1.DestroyAgentRequest
	(*DestroyAgentResponse)(nil),  // 9: jennahapi.agent.v1.DestroyAgentResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_jennah_agent_v1_agent_proto_depIdxs = []int32{
	0,  // 0: jennahapi.agent.v1.AgentInstance.status:type_name -> jennahapi.agent.v1.AgentStatus
	10, // 1: jennahapi.agent.v1.AgentInstance.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: jennahapi.agent.v1.SpawnAgentResponse.agent:type_name -> jennahapi.agent.v1.AgentInstance
	1,  // 3: jennahapi.agent.v1.GetAgentResponse.agent:type_name -> jennahapi.agent.v1.AgentInstance
	1,  // 4: jennahapi.agent.v1.ListAgentsResponse.agents:type_name -> jennahapi.agent.v1.AgentInstance
	10, // 5: jennahapi.agent.v1.DestroyAgentResponse.deleted_at:type_name -> google.protobuf.Timestamp
	2,  // 6: jennahapi.agent.v1.AgentService.SpawnAgent:input_type -> jennahapi.agent.v1.SpawnAgentRequest
	4,  // 7: jennahapi.agent.v1.AgentService.GetAgent:input_type -> jennahapi.agent.v1.GetAgentRequest
	6,  // 8: jennahapi.agent.v1.AgentService.ListAgents:input_type -> jennahapi.agent.v1.ListAgentsRequest
	8,  // 9: jennahapi.agent.v1.AgentService.DestroyAgent:input_type -> jennahapi.agent.v1.DestroyAgentRequest
	3,  // 10: jennahapi.agent.v1.AgentService.SpawnAgent:output_type -> jennahapi.agent.v1.SpawnAgentResponse
	5,  // 11: jennahapi.agent.v1.AgentService.GetAgent:output_type -> jennahapi.agent.v1.GetAgentResponse
	7,  // 12: jennahapi.agent.v1.AgentService.ListAgents:output_type -> jennahapi.agent.v1.ListAgentsResponse
	9,  // 13: jennahapi.agent.v1.AgentService.DestroyAgent:output_type -> jennahapi.agent.v1.DestroyAgentResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_jennah_agent_v1_agent_proto_init() }
func file_jennah_agent_v1_agent_proto_init() {
	if File_jennah_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jennah_agent_v1_agent_proto_rawDesc), len(file_jennah_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jennah_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_jennah_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_jennah_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_jennah_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_jennah_agent_v1_agent_proto = out.File
	file_jennah_agent_v1_agent_proto_goTypes = nil
	file_jennah_agent_v1_agent_proto_depIdxs = nil
}
