// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jennah/agent/v1/memory.proto

package agent

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction of vector+graph fusion when a query links the two sections.
type FusionDirection int32

const (
	FusionDirection_FUSION_DIRECTION_UNSPECIFIED FusionDirection = 0 // treated as VECTOR_FIRST
	// ANN vector search produces candidate nodes, then the graph traverses from
	// them. This is the default.
	FusionDirection_FUSION_DIRECTION_VECTOR_FIRST FusionDirection = 1
	// Graph traversal produces a candidate set, then it is ranked by EXACT vector
	// distance (not the ANN index).
	FusionDirection_FUSION_DIRECTION_GRAPH_FIRST FusionDirection = 2
)

// Enum value maps for FusionDirection.
var (
	FusionDirection_name = map[int32]string{
		0: "FUSION_DIRECTION_UNSPECIFIED",
		1: "FUSION_DIRECTION_VECTOR_FIRST",
		2: "FUSION_DIRECTION_GRAPH_FIRST",
	}
	FusionDirection_value = map[string]int32{
		"FUSION_DIRECTION_UNSPECIFIED":  0,
		"FUSION_DIRECTION_VECTOR_FIRST": 1,
		"FUSION_DIRECTION_GRAPH_FIRST":  2,
	}
)

func (x FusionDirection) Enum() *FusionDirection {
	p := new(FusionDirection)
	*p = x
	return p
}

func (x FusionDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FusionDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_agent_v1_memory_proto_enumTypes[0].Descriptor()
}

func (FusionDirection) Type() protoreflect.EnumType {
	return &file_jennah_agent_v1_memory_proto_enumTypes[0]
}

func (x FusionDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FusionDirection.Descriptor instead.
func (FusionDirection) EnumDescriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{0}
}

// Traversal direction of a hop relative to the current node.
type GraphDirection int32

const (
	GraphDirection_GRAPH_DIRECTION_UNSPECIFIED GraphDirection = 0 // treated as OUTGOING
	GraphDirection_GRAPH_DIRECTION_OUTGOING    GraphDirection = 1 // (current)-[edge]->(next)
	GraphDirection_GRAPH_DIRECTION_INCOMING    GraphDirection = 2 // (current)<-[edge]-(next)
	GraphDirection_GRAPH_DIRECTION_ANY         GraphDirection = 3 // (current)-[edge]-(next), either direction
)

// Enum value maps for GraphDirection.
var (
	GraphDirection_name = map[int32]string{
		0: "GRAPH_DIRECTION_UNSPECIFIED",
		1: "GRAPH_DIRECTION_OUTGOING",
		2: "GRAPH_DIRECTION_INCOMING",
		3: "GRAPH_DIRECTION_ANY",
	}
	GraphDirection_value = map[string]int32{
		"GRAPH_DIRECTION_UNSPECIFIED": 0,
		"GRAPH_DIRECTION_OUTGOING":    1,
		"GRAPH_DIRECTION_INCOMING":    2,
		"GRAPH_DIRECTION_ANY":         3,
	}
)

func (x GraphDirection) Enum() *GraphDirection {
	p := new(GraphDirection)
	*p = x
	return p
}

func (x GraphDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GraphDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_agent_v1_memory_proto_enumTypes[1].Descriptor()
}

func (GraphDirection) Type() protoreflect.EnumType {
	return &file_jennah_agent_v1_memory_proto_enumTypes[1]
}

func (x GraphDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GraphDirection.Descriptor instead.
func (GraphDirection) EnumDescriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{1}
}

// Request for MemoryService.CommitMemory.
//
// Any subset of the three section fields may be present; at least one SHOULD
// be. All present sections are written in the same transaction.
type CommitMemoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentInstanceId string                 `protobuf:"bytes,1,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"` // route path parameter; never read from the body
	// Execution-log section: a single step the agent recorded. Absent to commit
	// no log step.
	Log *ExecutionLogStep `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	// Vector section: chunks to upsert (write-or-replace) within the agent slice.
	// Empty to commit no vectors.
	Vectors []*VectorChunk `protobuf:"bytes,3,rep,name=vectors,proto3" json:"vectors,omitempty"`
	// Graph section: node and/or edge writes. Absent to commit no graph data.
	Graph         *GraphWrite `protobuf:"bytes,4,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMemoryRequest) Reset() {
	*x = CommitMemoryRequest{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMemoryRequest) ProtoMessage() {}

func (x *CommitMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMemoryRequest.ProtoReflect.Descriptor instead.
func (*CommitMemoryRequest) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *CommitMemoryRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *CommitMemoryRequest) GetLog() *ExecutionLogStep {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *CommitMemoryRequest) GetVectors() []*VectorChunk {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *CommitMemoryRequest) GetGraph() *GraphWrite {
	if x != nil {
		return x.Graph
	}
	return nil
}

// A single execution-memory step. On CommitMemory only the payload fields are
// read; `timestamp` is OUTPUT-ONLY (server-assigned) and populated when the
// step is read back via QueryMemory's log section.
type ExecutionLogStep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StepId         string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"` // caller-chosen; unique within the agent slice
	ThoughtProcess string                 `protobuf:"bytes,2,opt,name=thought_process,json=thoughtProcess,proto3" json:"thought_process,omitempty"`
	ToolUsed       string                 `protobuf:"bytes,3,opt,name=tool_used,json=toolUsed,proto3" json:"tool_used,omitempty"`
	ToolInput      string                 `protobuf:"bytes,4,opt,name=tool_input,json=toolInput,proto3" json:"tool_input,omitempty"`
	ToolOutput     string                 `protobuf:"bytes,5,opt,name=tool_output,json=toolOutput,proto3" json:"tool_output,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // output-only; server commit timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionLogStep) Reset() {
	*x = ExecutionLogStep{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLogStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLogStep) ProtoMessage() {}

func (x *ExecutionLogStep) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLogStep.ProtoReflect.Descriptor instead.
func (*ExecutionLogStep) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionLogStep) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecutionLogStep) GetThoughtProcess() string {
	if x != nil {
		return x.ThoughtProcess
	}
	return ""
}

func (x *ExecutionLogStep) GetToolUsed() string {
	if x != nil {
		return x.ToolUsed
	}
	return ""
}

func (x *ExecutionLogStep) GetToolInput() string {
	if x != nil {
		return x.ToolInput
	}
	return ""
}

func (x *ExecutionLogStep) GetToolOutput() string {
	if x != nil {
		return x.ToolOutput
	}
	return ""
}

func (x *ExecutionLogStep) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// A semantic-memory chunk to upsert.
type VectorChunk struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChunkId    string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // caller-chosen; unique within the agent slice
	RawContent string                 `protobuf:"bytes,2,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	// Optional precomputed embedding. When empty, the gateway generates it from
	// raw_content server-side (Vertex AI, task_type RETRIEVAL_DOCUMENT). When
	// supplied, its length MUST equal the data-plane database's configured
	// embedding width or the whole commit is rejected. float (32-bit) matches the
	// store's ARRAY<FLOAT32> vector column.
	Embedding     []float32 `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorChunk) Reset() {
	*x = VectorChunk{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorChunk) ProtoMessage() {}

func (x *VectorChunk) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorChunk.ProtoReflect.Descriptor instead.
func (*VectorChunk) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *VectorChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *VectorChunk) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *VectorChunk) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// Graph-memory writes for one commit. Edges may only connect nodes within the
// same (EnterpriseId, AgentInstanceId) slice. (Edges are point-in-time facts;
// bi-temporal validity and caller-driven supersession are a follow-on change
// and are intentionally not modeled here yet.)
type GraphWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphWrite) Reset() {
	*x = GraphWrite{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphWrite) ProtoMessage() {}

func (x *GraphWrite) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphWrite.ProtoReflect.Descriptor instead.
func (*GraphWrite) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *GraphWrite) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphWrite) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphNode struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	NodeId     string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // caller-chosen; unique within the agent slice
	Label      string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Properties *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"` // free-form JSON properties
	// Output-only: the row's last-write commit timestamp, populated when the node
	// is read back via InspectMemory. Nodes are written create-or-replace, so this
	// is the last write, not first creation. Ignored on CommitMemory.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *GraphNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GraphNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GraphNode) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GraphNode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GraphEdge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EdgeId           string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`                     // caller-chosen; unique within the agent slice
	SourceNodeId     string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"` // must reference a GraphNode in the same slice
	TargetNodeId     string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // must reference a GraphNode in the same slice
	RelationshipType string                 `protobuf:"bytes,4,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	Properties       *structpb.Struct       `protobuf:"bytes,5,opt,name=properties,proto3" json:"properties,omitempty"` // free-form JSON properties
	// Output-only: the row's last-write commit timestamp, populated when the edge
	// is read back via InspectMemory. Edges are written create-or-replace, so this
	// is the last write, not first creation. Ignored on CommitMemory.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *GraphEdge) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *GraphEdge) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *GraphEdge) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *GraphEdge) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *GraphEdge) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GraphEdge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// The commit receipt: a commit timestamp plus how many rows were written per
// memory type, so a caller can evidence exactly what the atomic step persisted.
type CommitMemoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommitTimestamp  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=commit_timestamp,json=commitTimestamp,proto3" json:"commit_timestamp,omitempty"`
	ExecutionLogRows int64                  `protobuf:"varint,2,opt,name=execution_log_rows,json=executionLogRows,proto3" json:"execution_log_rows,omitempty"`
	VectorRows       int64                  `protobuf:"varint,3,opt,name=vector_rows,json=vectorRows,proto3" json:"vector_rows,omitempty"`
	GraphNodeRows    int64                  `protobuf:"varint,4,opt,name=graph_node_rows,json=graphNodeRows,proto3" json:"graph_node_rows,omitempty"`
	GraphEdgeRows    int64                  `protobuf:"varint,5,opt,name=graph_edge_rows,json=graphEdgeRows,proto3" json:"graph_edge_rows,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommitMemoryResponse) Reset() {
	*x = CommitMemoryResponse{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMemoryResponse) ProtoMessage() {}

func (x *CommitMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMemoryResponse.ProtoReflect.Descriptor instead.
func (*CommitMemoryResponse) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *CommitMemoryResponse) GetCommitTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CommitTimestamp
	}
	return nil
}

func (x *CommitMemoryResponse) GetExecutionLogRows() int64 {
	if x != nil {
		return x.ExecutionLogRows
	}
	return 0
}

func (x *CommitMemoryResponse) GetVectorRows() int64 {
	if x != nil {
		return x.VectorRows
	}
	return 0
}

func (x *CommitMemoryResponse) GetGraphNodeRows() int64 {
	if x != nil {
		return x.GraphNodeRows
	}
	return 0
}

func (x *CommitMemoryResponse) GetGraphEdgeRows() int64 {
	if x != nil {
		return x.GraphEdgeRows
	}
	return 0
}

// Request for MemoryService.QueryMemory.
//
// Any subset of the three section fields may be present. All present sections
// are evaluated at one read timestamp.
type QueryMemoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentInstanceId string                 `protobuf:"bytes,1,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"` // route path parameter; never read from the body
	// Semantic (vector/ANN) section. Absent to skip semantic retrieval.
	Semantic *SemanticQuery `protobuf:"bytes,2,opt,name=semantic,proto3" json:"semantic,omitempty"`
	// Graph (structured traversal) section. Absent to skip graph retrieval.
	Graph *GraphQuery `protobuf:"bytes,3,opt,name=graph,proto3" json:"graph,omitempty"`
	// Execution-log recency section. Absent to skip the log.
	Log *LogQuery `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	// When true, the semantic and graph sections are composed and an additional
	// `fused` result is returned. Requires both of those sections to be present.
	Link bool `protobuf:"varint,5,opt,name=link,proto3" json:"link,omitempty"`
	// Fusion direction when `link` is set. Unspecified defaults to VECTOR_FIRST.
	FusionDirection FusionDirection `protobuf:"varint,6,opt,name=fusion_direction,json=fusionDirection,proto3,enum=jennahapi.agent.v1.FusionDirection" json:"fusion_direction,omitempty"`
	// Optional as-of read timestamp, applied UNIFORMLY to every section so all
	// sections observe the same historical instant. Empty reads the latest data.
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMemoryRequest) Reset() {
	*x = QueryMemoryRequest{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMemoryRequest) ProtoMessage() {}

func (x *QueryMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMemoryRequest.ProtoReflect.Descriptor instead.
func (*QueryMemoryRequest) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *QueryMemoryRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *QueryMemoryRequest) GetSemantic() *SemanticQuery {
	if x != nil {
		return x.Semantic
	}
	return nil
}

func (x *QueryMemoryRequest) GetGraph() *GraphQuery {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *QueryMemoryRequest) GetLog() *LogQuery {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *QueryMemoryRequest) GetLink() bool {
	if x != nil {
		return x.Link
	}
	return false
}

func (x *QueryMemoryRequest) GetFusionDirection() FusionDirection {
	if x != nil {
		return x.FusionDirection
	}
	return FusionDirection_FUSION_DIRECTION_UNSPECIFIED
}

func (x *QueryMemoryRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

// Semantic-section query. Exactly one of `embedding` or `query_text` MUST be
// supplied; when `query_text` is given the gateway embeds it server-side
// (task_type RETRIEVAL_QUERY). Results are ranked by ascending cosine distance
// and clamped to the caller's agent slice (the clamp never silently truncates
// below `limit`).
type SemanticQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`         // precomputed query embedding; width must match the db
	QueryText     string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"` // embedded server-side when `embedding` is absent
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                         // max matches to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticQuery) Reset() {
	*x = SemanticQuery{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticQuery) ProtoMessage() {}

func (x *SemanticQuery) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticQuery.ProtoReflect.Descriptor instead.
func (*SemanticQuery) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *SemanticQuery) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *SemanticQuery) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *SemanticQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Graph-section query: a STRUCTURED traversal over the agent's
// AgentKnowledgeGraph. The gateway BUILDS the GQL server-side from these typed
// fields, so no caller-authored query text is ever executed: every generated
// pattern element carries the (EnterpriseId, AgentInstanceId) clamp
// unconditionally and the slice cannot be widened. All caller values bind as
// query parameters; the few caller-supplied identifiers (property keys) are
// validated against a strict allowlist. This is the "structural injection, not
// trust" clamp — a free-form GQL string surface was rejected because it would
// require parsing and rewriting untrusted query text.
//
// A query is an anchor node set plus zero or more single-hop traversals. Each
// hop is one `GraphStep`; multi-hop traversal is expressed as successive steps.
type GraphQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *GraphNodeMatch        `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`  // anchor node set the traversal begins from
	Steps         []*GraphStep           `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`  // single-hop traversals; empty returns the anchor set
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // max rows; <= 0 uses the default, clamped to a server max
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphQuery) Reset() {
	*x = GraphQuery{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphQuery) ProtoMessage() {}

func (x *GraphQuery) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphQuery.ProtoReflect.Descriptor instead.
func (*GraphQuery) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{9}
}

func (x *GraphQuery) GetStart() *GraphNodeMatch {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GraphQuery) GetSteps() []*GraphStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GraphQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// A node-pattern constraint. `label` optionally filters the node's semantic
// `Label` property (e.g. "Person"); `filters` are optional equality predicates.
// The gateway always adds the (EnterpriseId, AgentInstanceId) clamp to the
// generated element — it is NOT expressible here and cannot be overridden.
type GraphNodeMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`     // optional equality filter on the node's `Label`
	Filters       []*PropertyFilter      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"` // optional property equality filters (values bound)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNodeMatch) Reset() {
	*x = GraphNodeMatch{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNodeMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNodeMatch) ProtoMessage() {}

func (x *GraphNodeMatch) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNodeMatch.ProtoReflect.Descriptor instead.
func (*GraphNodeMatch) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{10}
}

func (x *GraphNodeMatch) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GraphNodeMatch) GetFilters() []*PropertyFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

// One single-hop traversal to an adjacent node.
type GraphStep struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RelationshipType string                 `protobuf:"bytes,1,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`   // optional equality filter on the edge's `RelationshipType`
	Direction        GraphDirection         `protobuf:"varint,2,opt,name=direction,proto3,enum=jennahapi.agent.v1.GraphDirection" json:"direction,omitempty"` // direction relative to the current node
	Node             *GraphNodeMatch        `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`                                                   // constraints on the node reached by this hop
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GraphStep) Reset() {
	*x = GraphStep{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStep) ProtoMessage() {}

func (x *GraphStep) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStep.ProtoReflect.Descriptor instead.
func (*GraphStep) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{11}
}

func (x *GraphStep) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *GraphStep) GetDirection() GraphDirection {
	if x != nil {
		return x.Direction
	}
	return GraphDirection_GRAPH_DIRECTION_UNSPECIFIED
}

func (x *GraphStep) GetNode() *GraphNodeMatch {
	if x != nil {
		return x.Node
	}
	return nil
}

// A single property equality filter. `key` is a property name validated as a
// safe identifier by the gateway (resolved to a first-class column when it is
// one — e.g. `NodeId`, `Label` — otherwise a JSON `Properties` key); `value`
// binds as a query parameter and is never interpolated into query text.
type PropertyFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyFilter) Reset() {
	*x = PropertyFilter{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyFilter) ProtoMessage() {}

func (x *PropertyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyFilter.ProtoReflect.Descriptor instead.
func (*PropertyFilter) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{12}
}

func (x *PropertyFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PropertyFilter) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Execution-log-section query: the agent's most recent steps in commit-
// timestamp order.
type LogQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // max steps to return
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`  // optional recency lower bound
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQuery) Reset() {
	*x = LogQuery{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQuery) ProtoMessage() {}

func (x *LogQuery) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQuery.ProtoReflect.Descriptor instead.
func (*LogQuery) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{13}
}

func (x *LogQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LogQuery) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// Response for MemoryService.QueryMemory. Each result section is present only
// when its corresponding request section was supplied. `fused` is present only
// when the request set `link`.
type QueryMemoryResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Semantic *SemanticResult        `protobuf:"bytes,1,opt,name=semantic,proto3" json:"semantic,omitempty"`
	Graph    *GraphResult           `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	Log      *LogResult             `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Fused    *FusedResult           `protobuf:"bytes,4,opt,name=fused,proto3" json:"fused,omitempty"`
	// The single read timestamp every section was evaluated at.
	ReadTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMemoryResponse) Reset() {
	*x = QueryMemoryResponse{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMemoryResponse) ProtoMessage() {}

func (x *QueryMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMemoryResponse.ProtoReflect.Descriptor instead.
func (*QueryMemoryResponse) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{14}
}

func (x *QueryMemoryResponse) GetSemantic() *SemanticResult {
	if x != nil {
		return x.Semantic
	}
	return nil
}

func (x *QueryMemoryResponse) GetGraph() *GraphResult {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *QueryMemoryResponse) GetLog() *LogResult {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *QueryMemoryResponse) GetFused() *FusedResult {
	if x != nil {
		return x.Fused
	}
	return nil
}

func (x *QueryMemoryResponse) GetReadTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadTimestamp
	}
	return nil
}

type SemanticResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*SemanticMatch       `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticResult) Reset() {
	*x = SemanticResult{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticResult) ProtoMessage() {}

func (x *SemanticResult) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticResult.ProtoReflect.Descriptor instead.
func (*SemanticResult) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{15}
}

func (x *SemanticResult) GetMatches() []*SemanticMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type SemanticMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	RawContent    string                 `protobuf:"bytes,2,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	Distance      float64                `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"` // cosine distance; smaller is closer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticMatch) Reset() {
	*x = SemanticMatch{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticMatch) ProtoMessage() {}

func (x *SemanticMatch) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticMatch.ProtoReflect.Descriptor instead.
func (*SemanticMatch) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{16}
}

func (x *SemanticMatch) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SemanticMatch) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *SemanticMatch) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// Graph traversal result rows. Each row carries the matched elements' key
// fields (node ids and labels, and edge relationship types) keyed by gateway-
// assigned binding names, so the shape is carried as a structured value rather
// than a fixed schema.
type GraphResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*structpb.Struct     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphResult) Reset() {
	*x = GraphResult{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResult) ProtoMessage() {}

func (x *GraphResult) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResult.ProtoReflect.Descriptor instead.
func (*GraphResult) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{17}
}

func (x *GraphResult) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

type LogResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*ExecutionLogStep    `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"` // timestamp-populated records, newest first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResult) Reset() {
	*x = LogResult{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResult) ProtoMessage() {}

func (x *LogResult) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResult.ProtoReflect.Descriptor instead.
func (*LogResult) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{18}
}

func (x *LogResult) GetSteps() []*ExecutionLogStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// The linked semantic+graph view. Its exact shape depends on fusion direction
// and is carried as structured values until the fused-result schema is pinned
// down; see the unified-memory spec's fusion requirements.
type FusedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*structpb.Struct     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FusedResult) Reset() {
	*x = FusedResult{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FusedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FusedResult) ProtoMessage() {}

func (x *FusedResult) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FusedResult.ProtoReflect.Descriptor instead.
func (*FusedResult) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{19}
}

func (x *FusedResult) GetItems() []*structpb.Struct {
	if x != nil {
		return x.Items
	}
	return nil
}

// Request for MemoryService.InspectMemory.
//
// Any subset of the three section fields may be present; at least one SHOULD
// be. All present sections are enumerated at one read snapshot within the
// caller's (EnterpriseId, AgentInstanceId) slice. There is no query anchor:
// unlike QueryMemory this lists stored rows for debugging, so a section is
// requested simply by being present, bounded by its limit.
type InspectMemoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentInstanceId string                 `protobuf:"bytes,1,opt,name=agent_instance_id,json=agentInstanceId,proto3" json:"agent_instance_id,omitempty"` // route path parameter; never read from the body
	// Vector section: list stored chunks (content only). Absent to skip vectors.
	Vectors *InspectVectors `protobuf:"bytes,2,opt,name=vectors,proto3" json:"vectors,omitempty"`
	// Graph section: list stored nodes and edges. Absent to skip the graph.
	Graph *InspectGraph `protobuf:"bytes,3,opt,name=graph,proto3" json:"graph,omitempty"`
	// Execution-log section: list recent steps. Absent to skip the log.
	Log *InspectLog `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
	// Optional as-of read timestamp, applied UNIFORMLY to every section so all
	// sections observe the same historical instant. Empty reads the latest data.
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectMemoryRequest) Reset() {
	*x = InspectMemoryRequest{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectMemoryRequest) ProtoMessage() {}

func (x *InspectMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectMemoryRequest.ProtoReflect.Descriptor instead.
func (*InspectMemoryRequest) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{20}
}

func (x *InspectMemoryRequest) GetAgentInstanceId() string {
	if x != nil {
		return x.AgentInstanceId
	}
	return ""
}

func (x *InspectMemoryRequest) GetVectors() *InspectVectors {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *InspectMemoryRequest) GetGraph() *InspectGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *InspectMemoryRequest) GetLog() *InspectLog {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *InspectMemoryRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

// Vector-section listing request. Enumerates stored chunks; the embedding vector
// is never included in the response (it is large and not human-inspectable).
type InspectVectors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // max chunks; <= 0 uses the default, clamped to a server max
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectVectors) Reset() {
	*x = InspectVectors{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectVectors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectVectors) ProtoMessage() {}

func (x *InspectVectors) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectVectors.ProtoReflect.Descriptor instead.
func (*InspectVectors) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{21}
}

func (x *InspectVectors) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Graph-section listing request. Enumerates stored nodes and edges independently
// (this is a raw dump, not a traversal), each bounded by its own limit.
type InspectGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeLimit     int32                  `protobuf:"varint,1,opt,name=node_limit,json=nodeLimit,proto3" json:"node_limit,omitempty"` // max nodes; <= 0 uses the default, clamped to a server max
	EdgeLimit     int32                  `protobuf:"varint,2,opt,name=edge_limit,json=edgeLimit,proto3" json:"edge_limit,omitempty"` // max edges; <= 0 uses the default, clamped to a server max
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectGraph) Reset() {
	*x = InspectGraph{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectGraph) ProtoMessage() {}

func (x *InspectGraph) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectGraph.ProtoReflect.Descriptor instead.
func (*InspectGraph) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{22}
}

func (x *InspectGraph) GetNodeLimit() int32 {
	if x != nil {
		return x.NodeLimit
	}
	return 0
}

func (x *InspectGraph) GetEdgeLimit() int32 {
	if x != nil {
		return x.EdgeLimit
	}
	return 0
}

// Execution-log-section listing request: the agent's most recent steps in
// commit-timestamp order (newest first). Mirrors LogQuery so callers can follow
// the log incrementally (poll with `since` advanced to the prior read).
type InspectLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // max steps to return
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`  // optional recency lower bound
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectLog) Reset() {
	*x = InspectLog{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectLog) ProtoMessage() {}

func (x *InspectLog) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectLog.ProtoReflect.Descriptor instead.
func (*InspectLog) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{23}
}

func (x *InspectLog) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *InspectLog) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// Response for MemoryService.InspectMemory. Each result section is present only
// when its corresponding request section was supplied.
type InspectMemoryResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Vectors *VectorInspectResult   `protobuf:"bytes,1,opt,name=vectors,proto3" json:"vectors,omitempty"`
	Graph   *GraphInspectResult    `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	Log     *LogResult             `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"` // same ExecutionLogStep records as QueryMemory
	// The single read timestamp every section was evaluated at.
	ReadTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectMemoryResponse) Reset() {
	*x = InspectMemoryResponse{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectMemoryResponse) ProtoMessage() {}

func (x *InspectMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectMemoryResponse.ProtoReflect.Descriptor instead.
func (*InspectMemoryResponse) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{24}
}

func (x *InspectMemoryResponse) GetVectors() *VectorInspectResult {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *InspectMemoryResponse) GetGraph() *GraphInspectResult {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *InspectMemoryResponse) GetLog() *LogResult {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *InspectMemoryResponse) GetReadTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadTimestamp
	}
	return nil
}

type VectorInspectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*VectorChunkInfo     `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorInspectResult) Reset() {
	*x = VectorInspectResult{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorInspectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorInspectResult) ProtoMessage() {}

func (x *VectorInspectResult) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorInspectResult.ProtoReflect.Descriptor instead.
func (*VectorInspectResult) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{25}
}

func (x *VectorInspectResult) GetChunks() []*VectorChunkInfo {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// A stored vector chunk WITHOUT its embedding. The embedding column is
// deliberately omitted: it is large and carries no debugging value in a listing.
type VectorChunkInfo struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChunkId    string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	RawContent string                 `protobuf:"bytes,2,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	// Output-only: the chunk's last-write commit timestamp. Chunks are upserted, so
	// this is the last write, not first creation.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorChunkInfo) Reset() {
	*x = VectorChunkInfo{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorChunkInfo) ProtoMessage() {}

func (x *VectorChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorChunkInfo.ProtoReflect.Descriptor instead.
func (*VectorChunkInfo) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{26}
}

func (x *VectorChunkInfo) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *VectorChunkInfo) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *VectorChunkInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Graph listing result: the stored nodes and edges themselves (reusing the same
// GraphNode/GraphEdge shapes CommitMemory writes), NOT traversal rows.
type GraphInspectResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphInspectResult) Reset() {
	*x = GraphInspectResult{}
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphInspectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphInspectResult) ProtoMessage() {}

func (x *GraphInspectResult) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_agent_v1_memory_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphInspectResult.ProtoReflect.Descriptor instead.
func (*GraphInspectResult) Descriptor() ([]byte, []int) {
	return file_jennah_agent_v1_memory_proto_rawDescGZIP(), []int{27}
}

func (x *GraphInspectResult) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphInspectResult) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_jennah_agent_v1_memory_proto protoreflect.FileDescriptor

const file_jennah_agent_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x1cjennah/agent/v1/memory.proto\x12\x12jennahapi.agent.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\x13CommitMemoryRequest\x12*\n" +
	"\x11agent_instance_id\x18\x01 \x01(\tR\x0fagentInstanceId\x126\n" +
	"\x03log\x18\x02 \x01(\v2$.jennahapi.agent.v1.ExecutionLogStepR\x03log\x129\n" +
	"\avectors\x18\x03 \x03(\v2\x1f.jennahapi.agent.v1.VectorChunkR\avectors\x124\n" +
	"\x05graph\x18\x04 \x01(\v2\x1e.jennahapi.agent.v1.GraphWriteR\x05graph\"\xeb\x01\n" +
	"\x10ExecutionLogStep\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12'\n" +
	"\x0fthought_process\x18\x02 \x01(\tR\x0ethoughtProcess\x12\x1b\n" +
	"\ttool_used\x18\x03 \x01(\tR\btoolUsed\x12\x1d\n" +
	"\n" +
	"tool_input\x18\x04 \x01(\tR\ttoolInput\x12\x1f\n" +
	"\vtool_output\x18\x05 \x01(\tR\n" +
	"toolOutput\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"g\n" +
	"\vVectorChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vraw_content\x18\x02 \x01(\tR\n" +
	"rawContent\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\"v\n" +
	"\n" +
	"GraphWrite\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.jennahapi.agent.v1.GraphNodeR\x05nodes\x123\n" +
	"\x05edges\x18\x02 \x03(\v2\x1d.jennahapi.agent.v1.GraphEdgeR\x05edges\"\xae\x01\n" +
	"\tGraphNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x91\x02\n" +
	"\tGraphEdge\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12+\n" +
	"\x11relationship_type\x18\x04 \x01(\tR\x10relationshipType\x127\n" +
	"\n" +
	"properties\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfc\x01\n" +
	"\x14CommitMemoryResponse\x12E\n" +
	"\x10commit_timestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcommitTimestamp\x12,\n" +
	"\x12execution_log_rows\x18\x02 \x01(\x03R\x10executionLogRows\x12\x1f\n" +
	"\vvector_rows\x18\x03 \x01(\x03R\n" +
	"vectorRows\x12&\n" +
	"\x0fgraph_node_rows\x18\x04 \x01(\x03R\rgraphNodeRows\x12&\n" +
	"\x0fgraph_edge_rows\x18\x05 \x01(\x03R\rgraphEdgeRows\"\xfa\x02\n" +
	"\x12QueryMemoryRequest\x12*\n" +
	"\x11agent_instance_id\x18\x01 \x01(\tR\x0fagentInstanceId\x12=\n" +
	"\bsemantic\x18\x02 \x01(\v2!.jennahapi.agent.v1.SemanticQueryR\bsemantic\x124\n" +
	"\x05graph\x18\x03 \x01(\v2\x1e.jennahapi.agent.v1.GraphQueryR\x05graph\x12.\n" +
	"\x03log\x18\x04 \x01(\v2\x1c.jennahapi.agent.v1.LogQueryR\x03log\x12\x12\n" +
	"\x04link\x18\x05 \x01(\bR\x04link\x12N\n" +
	"\x10fusion_direction\x18\x06 \x01(\x0e2#.jennahapi.agent.v1.FusionDirectionR\x0ffusionDirection\x12/\n" +
	"\x05as_of\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\"b\n" +
	"\rSemanticQuery\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x91\x01\n" +
	"\n" +
	"GraphQuery\x128\n" +
	"\x05start\x18\x01 \x01(\v2\".jennahapi.agent.v1.GraphNodeMatchR\x05start\x123\n" +
	"\x05steps\x18\x02 \x03(\v2\x1d.jennahapi.agent.v1.GraphStepR\x05steps\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"d\n" +
	"\x0eGraphNodeMatch\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12<\n" +
	"\afilters\x18\x02 \x03(\v2\".jennahapi.agent.v1.PropertyFilterR\afilters\"\xb2\x01\n" +
	"\tGraphStep\x12+\n" +
	"\x11relationship_type\x18\x01 \x01(\tR\x10relationshipType\x12@\n" +
	"\tdirection\x18\x02 \x01(\x0e2\".jennahapi.agent.v1.GraphDirectionR\tdirection\x126\n" +
	"\x04node\x18\x03 \x01(\v2\".jennahapi.agent.v1.GraphNodeMatchR\x04node\"P\n" +
	"\x0ePropertyFilter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value\"R\n" +
	"\bLogQuery\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\xb7\x02\n" +
	"\x13QueryMemoryResponse\x12>\n" +
	"\bsemantic\x18\x01 \x01(\v2\".jennahapi.agent.v1.SemanticResultR\bsemantic\x125\n" +
	"\x05graph\x18\x02 \x01(\v2\x1f.jennahapi.agent.v1.GraphResultR\x05graph\x12/\n" +
	"\x03log\x18\x03 \x01(\v2\x1d.jennahapi.agent.v1.LogResultR\x03log\x125\n" +
	"\x05fused\x18\x04 \x01(\v2\x1f.jennahapi.agent.v1.FusedResultR\x05fused\x12A\n" +
	"\x0eread_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rreadTimestamp\"M\n" +
	"\x0eSemanticResult\x12;\n" +
	"\amatches\x18\x01 \x03(\v2!.jennahapi.agent.v1.SemanticMatchR\amatches\"g\n" +
	"\rSemanticMatch\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vraw_content\x18\x02 \x01(\tR\n" +
	"rawContent\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x01R\bdistance\":\n" +
	"\vGraphResult\x12+\n" +
	"\x04rows\x18\x01 \x03(\v2\x17.google.protobuf.StructR\x04rows\"G\n" +
	"\tLogResult\x12:\n" +
	"\x05steps\x18\x01 \x03(\v2$.jennahapi.agent.v1.ExecutionLogStepR\x05steps\"<\n" +
	"\vFusedResult\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.google.protobuf.StructR\x05items\"\x9b\x02\n" +
	"\x14InspectMemoryRequest\x12*\n" +
	"\x11agent_instance_id\x18\x01 \x01(\tR\x0fagentInstanceId\x12<\n" +
	"\avectors\x18\x02 \x01(\v2\".jennahapi.agent.v1.InspectVectorsR\avectors\x126\n" +
	"\x05graph\x18\x03 \x01(\v2 .jennahapi.agent.v1.InspectGraphR\x05graph\x120\n" +
	"\x03log\x18\x04 \x01(\v2\x1e.jennahapi.agent.v1.InspectLogR\x03log\x12/\n" +
	"\x05as_of\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\"&\n" +
	"\x0eInspectVectors\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"L\n" +
	"\fInspectGraph\x12\x1d\n" +
	"\n" +
	"node_limit\x18\x01 \x01(\x05R\tnodeLimit\x12\x1d\n" +
	"\n" +
	"edge_limit\x18\x02 \x01(\x05R\tedgeLimit\"T\n" +
	"\n" +
	"InspectLog\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\x8c\x02\n" +
	"\x15InspectMemoryResponse\x12A\n" +
	"\avectors\x18\x01 \x01(\v2'.jennahapi.agent.v1.VectorInspectResultR\avectors\x12<\n" +
	"\x05graph\x18\x02 \x01(\v2&.jennahapi.agent.v1.GraphInspectResultR\x05graph\x12/\n" +
	"\x03log\x18\x03 \x01(\v2\x1d.jennahapi.agent.v1.LogResultR\x03log\x12A\n" +
	"\x0eread_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rreadTimestamp\"R\n" +
	"\x13VectorInspectResult\x12;\n" +
	"\x06chunks\x18\x01 \x03(\v2#.jennahapi.agent.v1.VectorChunkInfoR\x06chunks\"\x88\x01\n" +
	"\x0fVectorChunkInfo\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vraw_content\x18\x02 \x01(\tR\n" +
	"rawContent\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"~\n" +
	"\x12GraphInspectResult\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.jennahapi.agent.v1.GraphNodeR\x05nodes\x123\n" +
	"\x05edges\x18\x02 \x03(\v2\x1d.jennahapi.agent.v1.GraphEdgeR\x05edges*x\n" +
	"\x0fFusionDirection\x12 \n" +
	"\x1cFUSION_DIRECTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dFUSION_DIRECTION_VECTOR_FIRST\x10\x01\x12 \n" +
	"\x1cFUSION_DIRECTION_GRAPH_FIRST\x10\x02*\x86\x01\n" +
	"\x0eGraphDirection\x12\x1f\n" +
	"\x1bGRAPH_DIRECTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18GRAPH_DIRECTION_OUTGOING\x10\x01\x12\x1c\n" +
	"\x18GRAPH_DIRECTION_INCOMING\x10\x02\x12\x17\n" +
	"\x13GRAPH_DIRECTION_ANY\x10\x032\xe6\x03\n" +
	"\rMemoryService\x12\x9a\x01\n" +
	"\fCommitMemory\x12'.jennahapi.agent.v1.CommitMemoryRequest\x1a(.jennahapi.agent.v1.CommitMemoryResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/v1/agents/{agent_instance_id}/memory:commit\x12\x96\x01\n" +
	"\vQueryMemory\x12&.jennahapi.agent.v1.QueryMemoryRequest\x1a'.jennahapi.agent.v1.QueryMemoryResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/agents/{agent_instance_id}/memory:query\x12\x9e\x01\n" +
	"\rInspectMemory\x12(.jennahapi.agent.v1.InspectMemoryRequest\x1a).jennahapi.agent.v1.InspectMemoryResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/agents/{agent_instance_id}/memory:inspectB)Z'github.com/alphauslabs/jennah-api/agentb\x06proto3"

var (
	file_jennah_agent_v1_memory_proto_rawDescOnce sync.Once
	file_jennah_agent_v1_memory_proto_rawDescData []byte
)

func file_jennah_agent_v1_memory_proto_rawDescGZIP() []byte {
	file_jennah_agent_v1_memory_proto_rawDescOnce.Do(func() {
		file_jennah_agent_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jennah_agent_v1_memory_proto_rawDesc), len(file_jennah_agent_v1_memory_proto_rawDesc)))
	})
	return file_jennah_agent_v1_memory_proto_rawDescData
}

var file_jennah_agent_v1_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jennah_agent_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_jennah_agent_v1_memory_proto_goTypes = []any{
	(FusionDirection)(0),          // 0: jennahapi.agent.v1.FusionDirection
	(GraphDirection)(0),           // 1: jennahapi.agent.v1.GraphDirection
	(*CommitMemoryRequest)(nil),   // 2: jennahapi.agent.v1.CommitMemoryRequest
	(*ExecutionLogStep)(nil),      // 3: jennahapi.agent.v1.ExecutionLogStep
	(*VectorChunk)(nil),           // 4: jennahapi.agent.v1.VectorChunk
	(*GraphWrite)(nil),            // 5: jennahapi.agent.v1.GraphWrite
	(*GraphNode)(nil),             // 6: jennahapi.agent.v1.GraphNode
	(*GraphEdge)(nil),             // 7: jennahapi.agent.v1.GraphEdge
	(*CommitMemoryResponse)(nil),  // 8: jennahapi.agent.v1.CommitMemoryResponse
	(*QueryMemoryRequest)(nil),    // 9: jennahapi.agent.v1.QueryMemoryRequest
	(*SemanticQuery)(nil),         // 10: jennahapi.agent.v1.SemanticQuery
	(*GraphQuery)(nil),            // 11: jennahapi.agent.v1.GraphQuery
	(*GraphNodeMatch)(nil),        // 12: jennahapi.agent.v1.GraphNodeMatch
	(*GraphStep)(nil),             // 13: jennahapi.agent.v1.GraphStep
	(*PropertyFilter)(nil),        // 14: jennahapi.agent.v1.PropertyFilter
	(*LogQuery)(nil),              // 15: jennahapi.agent.v1.LogQuery
	(*QueryMemoryResponse)(nil),   // 16: jennahapi.agent.v1.QueryMemoryResponse
	(*SemanticResult)(nil),        // 17: jennahapi.agent.v1.SemanticResult
	(*SemanticMatch)(nil),         // 18: jennahapi.agent.v1.SemanticMatch
	(*GraphResult)(nil),           // 19: jennahapi.agent.v1.GraphResult
	(*LogResult)(nil),             // 20: jennahapi.agent.v1.LogResult
	(*FusedResult)(nil),           // 21: jennahapi.agent.v1.FusedResult
	(*InspectMemoryRequest)(nil),  // 22: jennahapi.agent.v1.InspectMemoryRequest
	(*InspectVectors)(nil),        // 23: jennahapi.agent.v1.InspectVectors
	(*InspectGraph)(nil),          // 24: jennahapi.agent.v1.InspectGraph
	(*InspectLog)(nil),            // 25: jennahapi.agent.v1.InspectLog
	(*InspectMemoryResponse)(nil), // 26: jennahapi.agent.v1.InspectMemoryResponse
	(*VectorInspectResult)(nil),   // 27: jennahapi.agent.v1.VectorInspectResult
	(*VectorChunkInfo)(nil),       // 28: jennahapi.agent.v1.VectorChunkInfo
	(*GraphInspectResult)(nil),    // 29: jennahapi.agent.v1.GraphInspectResult
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 31: google.protobuf.Struct
	(*structpb.Value)(nil),        // 32: google.protobuf.Value
}
var file_jennah_agent_v1_memory_proto_depIdxs = []int32{
	3,  // 0: jennahapi.agent.v1.CommitMemoryRequest.log:type_name -> jennahapi.agent.v1.ExecutionLogStep
	4,  // 1: jennahapi.agent.v1.CommitMemoryRequest.vectors:type_name -> jennahapi.agent.v1.VectorChunk
	5,  // 2: jennahapi.agent.v1.CommitMemoryRequest.graph:type_name -> jennahapi.agent.v1.GraphWrite
	30, // 3: jennahapi.agent.v1.ExecutionLogStep.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 4: jennahapi.agent.v1.GraphWrite.nodes:type_name -> jennahapi.agent.v1.GraphNode
	7,  // 5: jennahapi.agent.v1.GraphWrite.edges:type_name -> jennahapi.agent.v1.GraphEdge
	31, // 6: jennahapi.agent.v1.GraphNode.properties:type_name -> google.protobuf.Struct
	30, // 7: jennahapi.agent.v1.GraphNode.updated_at:type_name -> google.protobuf.Timestamp
	31, // 8: jennahapi.agent.v1.GraphEdge.properties:type_name -> google.protobuf.Struct
	30, // 9: jennahapi.agent.v1.GraphEdge.updated_at:type_name -> google.protobuf.Timestamp
	30, // 10: jennahapi.agent.v1.CommitMemoryResponse.commit_timestamp:type_name -> google.protobuf.Timestamp
	10, // 11: jennahapi.agent.v1.QueryMemoryRequest.semantic:type_name -> jennahapi.agent.v1.SemanticQuery
	11, // 12: jennahapi.agent.v1.QueryMemoryRequest.graph:type_name -> jennahapi.agent.v1.GraphQuery
	15, // 13: jennahapi.agent.v1.QueryMemoryRequest.log:type_name -> jennahapi.agent.v1.LogQuery
	0,  // 14: jennahapi.agent.v1.QueryMemoryRequest.fusion_direction:type_name -> jennahapi.agent.v1.FusionDirection
	30, // 15: jennahapi.agent.v1.QueryMemoryRequest.as_of:type_name -> google.protobuf.Timestamp
	12, // 16: jennahapi.agent.v1.GraphQuery.start:type_name -> jennahapi.agent.v1.GraphNodeMatch
	13, // 17: jennahapi.agent.v1.GraphQuery.steps:type_name -> jennahapi.agent.v1.GraphStep
	14, // 18: jennahapi.agent.v1.GraphNodeMatch.filters:type_name -> jennahapi.agent.v1.PropertyFilter
	1,  // 19: jennahapi.agent.v1.GraphStep.direction:type_name -> jennahapi.agent.v1.GraphDirection
	12, // 20: jennahapi.agent.v1.GraphStep.node:type_name -> jennahapi.agent.v1.GraphNodeMatch
	32, // 21: jennahapi.agent.v1.PropertyFilter.value:type_name -> google.protobuf.Value
	30, // 22: jennahapi.agent.v1.LogQuery.since:type_name -> google.protobuf.Timestamp
	17, // 23: jennahapi.agent.v1.QueryMemoryResponse.semantic:type_name -> jennahapi.agent.v1.SemanticResult
	19, // 24: jennahapi.agent.v1.QueryMemoryResponse.graph:type_name -> jennahapi.agent.v1.GraphResult
	20, // 25: jennahapi.agent.v1.QueryMemoryResponse.log:type_name -> jennahapi.agent.v1.LogResult
	21, // 26: jennahapi.agent.v1.QueryMemoryResponse.fused:type_name -> jennahapi.agent.v1.FusedResult
	30, // 27: jennahapi.agent.v1.QueryMemoryResponse.read_timestamp:type_name -> google.protobuf.Timestamp
	18, // 28: jennahapi.agent.v1.SemanticResult.matches:type_name -> jennahapi.agent.v1.SemanticMatch
	31, // 29: jennahapi.agent.v1.GraphResult.rows:type_name -> google.protobuf.Struct
	3,  // 30: jennahapi.agent.v1.LogResult.steps:type_name -> jennahapi.agent.v1.ExecutionLogStep
	31, // 31: jennahapi.agent.v1.FusedResult.items:type_name -> google.protobuf.Struct
	23, // 32: jennahapi.agent.v1.InspectMemoryRequest.vectors:type_name -> jennahapi.agent.v1.InspectVectors
	24, // 33: jennahapi.agent.v1.InspectMemoryRequest.graph:type_name -> jennahapi.agent.v1.InspectGraph
	25, // 34: jennahapi.agent.v1.InspectMemoryRequest.log:type_name -> jennahapi.agent.v1.InspectLog
	30, // 35: jennahapi.agent.v1.InspectMemoryRequest.as_of:type_name -> google.protobuf.Timestamp
	30, // 36: jennahapi.agent.v1.InspectLog.since:type_name -> google.protobuf.Timestamp
	27, // 37: jennahapi.agent.v1.InspectMemoryResponse.vectors:type_name -> jennahapi.agent.v1.VectorInspectResult
	29, // 38: jennahapi.agent.v1.InspectMemoryResponse.graph:type_name -> jennahapi.agent.v1.GraphInspectResult
	20, // 39: jennahapi.agent.v1.InspectMemoryResponse.log:type_name -> jennahapi.agent.v1.LogResult
	30, // 40: jennahapi.agent.v1.InspectMemoryResponse.read_timestamp:type_name -> google.protobuf.Timestamp
	28, // 41: jennahapi.agent.v1.VectorInspectResult.chunks:type_name -> jennahapi.agent.v1.VectorChunkInfo
	30, // 42: jennahapi.agent.v1.VectorChunkInfo.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 43: jennahapi.agent.v1.GraphInspectResult.nodes:type_name -> jennahapi.agent.v1.GraphNode
	7,  // 44: jennahapi.agent.v1.GraphInspectResult.edges:type_name -> jennahapi.agent.v1.GraphEdge
	2,  // 45: jennahapi.agent.v1.MemoryService.CommitMemory:input_type -> jennahapi.agent.v1.CommitMemoryRequest
	9,  // 46: jennahapi.agent.v1.MemoryService.QueryMemory:input_type -> jennahapi.agent.v1.QueryMemoryRequest
	22, // 47: jennahapi.agent.v1.MemoryService.InspectMemory:input_type -> jennahapi.agent.v1.InspectMemoryRequest
	8,  // 48: jennahapi.agent.v1.MemoryService.CommitMemory:output_type -> jennahapi.agent.v1.CommitMemoryResponse
	16, // 49: jennahapi.agent.v1.MemoryService.QueryMemory:output_type -> jennahapi.agent.v1.QueryMemoryResponse
	26, // 50: jennahapi.agent.v1.MemoryService.InspectMemory:output_type -> jennahapi.agent.v1.InspectMemoryResponse
	48, // [48:51] is the sub-list for method output_type
	45, // [45:48] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_jennah_agent_v1_memory_proto_init() }
func file_jennah_agent_v1_memory_proto_init() {
	if File_jennah_agent_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jennah_agent_v1_memory_proto_rawDesc), len(file_jennah_agent_v1_memory_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jennah_agent_v1_memory_proto_goTypes,
		DependencyIndexes: file_jennah_agent_v1_memory_proto_depIdxs,
		EnumInfos:         file_jennah_agent_v1_memory_proto_enumTypes,
		MessageInfos:      file_jennah_agent_v1_memory_proto_msgTypes,
	}.Build()
	File_jennah_agent_v1_memory_proto = out.File
	file_jennah_agent_v1_memory_proto_goTypes = nil
	file_jennah_agent_v1_memory_proto_depIdxs = nil
}
