// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jennah/billing/v1/billing.proto

package billing

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Which system owns an enterprise's tier. Ownership is exclusive: a write from a
// source that does not own the tier is rejected, which is what keeps two billing
// integrations from fighting over one enterprise.
//
// A client MUST NOT decide whether to show an in-app plan change by comparing
// against this enum — a source added after the client was built arrives as
// BILLING_SOURCE_UNSPECIFIED. Use `externally_managed`, which is computed
// server-side and stays correct across versions.
type BillingSource int32

const (
	// Unknown to this client's proto version — treat as external if
	// `externally_managed` says so.
	BillingSource_BILLING_SOURCE_UNSPECIFIED BillingSource = 0
	// Nobody is billing this enterprise yet: a trial. Stored as empty rather than a
	// literal, and it is the state the first paid subscription acquires rather than
	// contends for.
	BillingSource_BILLING_SOURCE_PLATFORM BillingSource = 1
	// A human intervention through the operator CLI. A source like any other: it
	// must own the tier or take ownership explicitly, so a support fix is as
	// auditable as a provider event.
	BillingSource_BILLING_SOURCE_OPERATOR BillingSource = 2
	// AWS Marketplace.
	BillingSource_BILLING_SOURCE_AWS_MARKETPLACE BillingSource = 3
)

// Enum value maps for BillingSource.
var (
	BillingSource_name = map[int32]string{
		0: "BILLING_SOURCE_UNSPECIFIED",
		1: "BILLING_SOURCE_PLATFORM",
		2: "BILLING_SOURCE_OPERATOR",
		3: "BILLING_SOURCE_AWS_MARKETPLACE",
	}
	BillingSource_value = map[string]int32{
		"BILLING_SOURCE_UNSPECIFIED":     0,
		"BILLING_SOURCE_PLATFORM":        1,
		"BILLING_SOURCE_OPERATOR":        2,
		"BILLING_SOURCE_AWS_MARKETPLACE": 3,
	}
)

func (x BillingSource) Enum() *BillingSource {
	p := new(BillingSource)
	*p = x
	return p
}

func (x BillingSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BillingSource) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_billing_v1_billing_proto_enumTypes[0].Descriptor()
}

func (BillingSource) Type() protoreflect.EnumType {
	return &file_jennah_billing_v1_billing_proto_enumTypes[0]
}

func (x BillingSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BillingSource.Descriptor instead.
func (BillingSource) EnumDescriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

// Lifecycle of one external subscription. The two non-obvious states exist
// because an absence of entitlements is ambiguous and a presence we cannot
// interpret is not a cancellation.
type SubscriptionState int32

const (
	SubscriptionState_SUBSCRIPTION_STATE_UNSPECIFIED SubscriptionState = 0
	// Resolved and persisted, but not yet attached to any enterprise. A normal,
	// persistent state — AWS bills from contract creation, so a buyer who abandons
	// registration still has a paid subscription that must not be lost.
	SubscriptionState_SUBSCRIPTION_STATE_UNBOUND SubscriptionState = 1
	// Bound to an enterprise with an active entitlement.
	SubscriptionState_SUBSCRIPTION_STATE_ACTIVE SubscriptionState = 2
	// An authoritative read returned no active entitlement, but the subscription is
	// still within the grace window of its last known expiration — where "renewing
	// right now" and "ended" are the same observation. The tier is held and the
	// subscription re-read; only an absence that outlasts the window cancels.
	SubscriptionState_SUBSCRIPTION_STATE_PENDING_VERIFICATION SubscriptionState = 3
	// Something needs a human: entitlements are present but none maps to a
	// configured tier, or the purchased quantity is greater than one. The tier is
	// left unchanged in both cases — a dimension we do not recognize must never be
	// read as a cancellation.
	SubscriptionState_SUBSCRIPTION_STATE_NEEDS_ATTENTION SubscriptionState = 4
	// The subscription ended: either an explicit end event from the provider, or an
	// absence confirmed past the grace window.
	SubscriptionState_SUBSCRIPTION_STATE_CANCELLED SubscriptionState = 5
)

// Enum value maps for SubscriptionState.
var (
	SubscriptionState_name = map[int32]string{
		0: "SUBSCRIPTION_STATE_UNSPECIFIED",
		1: "SUBSCRIPTION_STATE_UNBOUND",
		2: "SUBSCRIPTION_STATE_ACTIVE",
		3: "SUBSCRIPTION_STATE_PENDING_VERIFICATION",
		4: "SUBSCRIPTION_STATE_NEEDS_ATTENTION",
		5: "SUBSCRIPTION_STATE_CANCELLED",
	}
	SubscriptionState_value = map[string]int32{
		"SUBSCRIPTION_STATE_UNSPECIFIED":          0,
		"SUBSCRIPTION_STATE_UNBOUND":              1,
		"SUBSCRIPTION_STATE_ACTIVE":               2,
		"SUBSCRIPTION_STATE_PENDING_VERIFICATION": 3,
		"SUBSCRIPTION_STATE_NEEDS_ATTENTION":      4,
		"SUBSCRIPTION_STATE_CANCELLED":            5,
	}
)

func (x SubscriptionState) Enum() *SubscriptionState {
	p := new(SubscriptionState)
	*p = x
	return p
}

func (x SubscriptionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionState) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_billing_v1_billing_proto_enumTypes[1].Descriptor()
}

func (SubscriptionState) Type() protoreflect.EnumType {
	return &file_jennah_billing_v1_billing_proto_enumTypes[1]
}

func (x SubscriptionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionState.Descriptor instead.
func (SubscriptionState) EnumDescriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

// One subscription bound to an enterprise. The field names are provider-neutral
// so a second billing source needs no second message; each comment names the AWS
// Marketplace meaning.
type BoundSubscription struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source BillingSource          `protobuf:"varint,1,opt,name=source,proto3,enum=jennahapi.billing.v1.BillingSource" json:"source,omitempty"`
	// The provider's subscription identity. For AWS Marketplace this is the
	// agreement's LicenseArn — the identity used in logs, operator subcommands, and
	// support conversations. It is the agreement, not the buyer: one AWS account can
	// hold several concurrent agreements for the same product.
	SubscriptionId string `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// A provider-side account identifier the buyer can actually recognize. For AWS
	// Marketplace this is the buyer's AWS account id, which is what makes a support
	// claim ("that's my company's account") verifiable against a recorded fact.
	AccountRef string `protobuf:"bytes,3,opt,name=account_ref,json=accountRef,proto3" json:"account_ref,omitempty"`
	// The provider-side product identifier this subscription was resolved under. For
	// AWS Marketplace this is the product code, and it selects which configured
	// dimension mapping applies — a second listing is a second product code.
	ProductRef string `protobuf:"bytes,4,opt,name=product_ref,json=productRef,proto3" json:"product_ref,omitempty"`
	// The tier resolved for THIS subscription. An enterprise holding several active
	// subscriptions is entitled at the highest-ranked tier across them, which is
	// reported as `tier` on GetBillingStateResponse.
	Tier string `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	// Last known entitlement expiration. For a monthly contract this advances on
	// every renewal, so it is a boundary every customer crosses each cycle rather
	// than a once-a-year event.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	State     SubscriptionState      `protobuf:"varint,7,opt,name=state,proto3,enum=jennahapi.billing.v1.SubscriptionState" json:"state,omitempty"`
	// The purchased entitlement quantity. Recorded and surfaced but NOT enforced —
	// seat limits are out of scope — and it never affects the resolved tier. A value
	// above one is flagged for attention, because a buyer billed for five units and
	// silently receiving one unit's service is the failure worth being loud about.
	Quantity      int64 `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundSubscription) Reset() {
	*x = BoundSubscription{}
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundSubscription) ProtoMessage() {}

func (x *BoundSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundSubscription.ProtoReflect.Descriptor instead.
func (*BoundSubscription) Descriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *BoundSubscription) GetSource() BillingSource {
	if x != nil {
		return x.Source
	}
	return BillingSource_BILLING_SOURCE_UNSPECIFIED
}

func (x *BoundSubscription) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *BoundSubscription) GetAccountRef() string {
	if x != nil {
		return x.AccountRef
	}
	return ""
}

func (x *BoundSubscription) GetProductRef() string {
	if x != nil {
		return x.ProductRef
	}
	return ""
}

func (x *BoundSubscription) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *BoundSubscription) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *BoundSubscription) GetState() SubscriptionState {
	if x != nil {
		return x.State
	}
	return SubscriptionState_SUBSCRIPTION_STATE_UNSPECIFIED
}

func (x *BoundSubscription) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Request message for the BillingService.GetBillingState rpc.
type GetBillingStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingStateRequest) Reset() {
	*x = GetBillingStateRequest{}
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingStateRequest) ProtoMessage() {}

func (x *GetBillingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingStateRequest.ProtoReflect.Descriptor instead.
func (*GetBillingStateRequest) Descriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

// Response message for the BillingService.GetBillingState rpc.
type GetBillingStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The active enterprise's effective tier — the highest-ranked tier across its
	// active subscriptions, or its platform-assigned tier when nothing is bound.
	Tier string `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"`
	// The source that owns the tier, for display.
	Source BillingSource `protobuf:"varint,2,opt,name=source,proto3,enum=jennahapi.billing.v1.BillingSource" json:"source,omitempty"`
	// The raw owning-source identifier as stored, empty for a platform-owned (trial)
	// enterprise. Present so a source newer than the client's proto version is still
	// nameable in a support conversation and in logs.
	SourceId string `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// True when the tier is owned by an external billing source. This is the field a
	// client switches on: when it is true, suppress every in-app plan-change
	// affordance and direct the user to `manage_url`. Computed server-side so it
	// stays correct for a source the client does not know about.
	ExternallyManaged bool `protobuf:"varint,4,opt,name=externally_managed,json=externallyManaged,proto3" json:"externally_managed,omitempty"`
	// Every subscription bound to the active enterprise. Plural because concurrent
	// agreements are legitimate: a second team buying separately, an early
	// re-purchase, or a channel-partner offer alongside a direct one. Empty for a
	// trial enterprise.
	Subscriptions []*BoundSubscription `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// Where the plan is managed when it is externally owned — the AWS Marketplace
	// subscription page for a marketplace-owned enterprise. Also the renewal path
	// shown when the tier is the terminal cancelled one, so a former subscriber gets
	// a re-subscribe link rather than an expired-trial prompt. Empty when the plan is
	// platform-owned.
	ManageUrl     string `protobuf:"bytes,6,opt,name=manage_url,json=manageUrl,proto3" json:"manage_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingStateResponse) Reset() {
	*x = GetBillingStateResponse{}
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingStateResponse) ProtoMessage() {}

func (x *GetBillingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingStateResponse.ProtoReflect.Descriptor instead.
func (*GetBillingStateResponse) Descriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillingStateResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *GetBillingStateResponse) GetSource() BillingSource {
	if x != nil {
		return x.Source
	}
	return BillingSource_BILLING_SOURCE_UNSPECIFIED
}

func (x *GetBillingStateResponse) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *GetBillingStateResponse) GetExternallyManaged() bool {
	if x != nil {
		return x.ExternallyManaged
	}
	return false
}

func (x *GetBillingStateResponse) GetSubscriptions() []*BoundSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *GetBillingStateResponse) GetManageUrl() string {
	if x != nil {
		return x.ManageUrl
	}
	return ""
}

// Request message for the BillingService.BindMarketplaceRegistration rpc.
type BindMarketplaceRegistrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The single-use handle carried on the redirect from the public registration
	// endpoint. Short-lived, consumed on the first successful bind, and stored only
	// as a hash so a database read cannot recover a usable handle.
	Handle        string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMarketplaceRegistrationRequest) Reset() {
	*x = BindMarketplaceRegistrationRequest{}
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMarketplaceRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMarketplaceRegistrationRequest) ProtoMessage() {}

func (x *BindMarketplaceRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMarketplaceRegistrationRequest.ProtoReflect.Descriptor instead.
func (*BindMarketplaceRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *BindMarketplaceRegistrationRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// Response message for the BillingService.BindMarketplaceRegistration rpc.
type BindMarketplaceRegistrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The subscription as bound, so the console can render the resulting plan
	// without a second call.
	Subscription *BoundSubscription `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// The enterprise's effective tier after the bind.
	Tier string `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	// True when this bind actually moved the tier. A tier change invalidates the
	// enterprise's outstanding access tokens (they carry the tier and are verified
	// with no database lookup), so the client must refresh before the new plan takes
	// effect. Stated explicitly rather than left implicit — a customer who just paid
	// and is still blocked files a ticket.
	//
	// NOT always true. Re-binding a subscription already attached to the same
	// enterprise is idempotent success and changes nothing, so no refresh is needed;
	// buyers re-enter through the provider's "set up your account" link routinely. A
	// client that refreshes unconditionally rotates a session token for no reason.
	AccessTokenRefreshRequired bool `protobuf:"varint,3,opt,name=access_token_refresh_required,json=accessTokenRefreshRequired,proto3" json:"access_token_refresh_required,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *BindMarketplaceRegistrationResponse) Reset() {
	*x = BindMarketplaceRegistrationResponse{}
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMarketplaceRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMarketplaceRegistrationResponse) ProtoMessage() {}

func (x *BindMarketplaceRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMarketplaceRegistrationResponse.ProtoReflect.Descriptor instead.
func (*BindMarketplaceRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *BindMarketplaceRegistrationResponse) GetSubscription() *BoundSubscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *BindMarketplaceRegistrationResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *BindMarketplaceRegistrationResponse) GetAccessTokenRefreshRequired() bool {
	if x != nil {
		return x.AccessTokenRefreshRequired
	}
	return false
}

// Request message for the BillingService.ResolveMarketplaceRegistration rpc.
type ResolveMarketplaceRegistrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The `x-amzn-marketplace-token` form field, verbatim as AWS posted it.
	RegistrationToken string `protobuf:"bytes,1,opt,name=registration_token,json=registrationToken,proto3" json:"registration_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveMarketplaceRegistrationRequest) Reset() {
	*x = ResolveMarketplaceRegistrationRequest{}
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMarketplaceRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMarketplaceRegistrationRequest) ProtoMessage() {}

func (x *ResolveMarketplaceRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMarketplaceRegistrationRequest.ProtoReflect.Descriptor instead.
func (*ResolveMarketplaceRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveMarketplaceRegistrationRequest) GetRegistrationToken() string {
	if x != nil {
		return x.RegistrationToken
	}
	return ""
}

// Response message for the BillingService.ResolveMarketplaceRegistration rpc.
type ResolveMarketplaceRegistrationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The absolute console URL to redirect the browser to, with the single-use
	// binding handle already embedded. The backend builds it, because the backend is
	// what holds the configured console origin and validates it against the app-
	// redirect allowlist; the edge only issues the 302.
	//
	// The handle is deliberately NOT returned as a separate field. It is a bearer
	// capability, and there is no consumer for it apart from this URL.
	RedirectUrl   string `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMarketplaceRegistrationResponse) Reset() {
	*x = ResolveMarketplaceRegistrationResponse{}
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMarketplaceRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMarketplaceRegistrationResponse) ProtoMessage() {}

func (x *ResolveMarketplaceRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMarketplaceRegistrationResponse.ProtoReflect.Descriptor instead.
func (*ResolveMarketplaceRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_jennah_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveMarketplaceRegistrationResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

var File_jennah_billing_v1_billing_proto protoreflect.FileDescriptor

const file_jennah_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1fjennah/billing/v1/billing.proto\x12\x14jennahapi.billing.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x02\n" +
	"\x11BoundSubscription\x12;\n" +
	"\x06source\x18\x01 \x01(\x0e2#.jennahapi.billing.v1.BillingSourceR\x06source\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x1f\n" +
	"\vaccount_ref\x18\x03 \x01(\tR\n" +
	"accountRef\x12\x1f\n" +
	"\vproduct_ref\x18\x04 \x01(\tR\n" +
	"productRef\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12=\n" +
	"\x05state\x18\a \x01(\x0e2'.jennahapi.billing.v1.SubscriptionStateR\x05state\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x03R\bquantity\"\x18\n" +
	"\x16GetBillingStateRequest\"\xa4\x02\n" +
	"\x17GetBillingStateResponse\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12;\n" +
	"\x06source\x18\x02 \x01(\x0e2#.jennahapi.billing.v1.BillingSourceR\x06source\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12-\n" +
	"\x12externally_managed\x18\x04 \x01(\bR\x11externallyManaged\x12M\n" +
	"\rsubscriptions\x18\x05 \x03(\v2'.jennahapi.billing.v1.BoundSubscriptionR\rsubscriptions\x12\x1d\n" +
	"\n" +
	"manage_url\x18\x06 \x01(\tR\tmanageUrl\"<\n" +
	"\"BindMarketplaceRegistrationRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"\xc9\x01\n" +
	"#BindMarketplaceRegistrationResponse\x12K\n" +
	"\fsubscription\x18\x01 \x01(\v2'.jennahapi.billing.v1.BoundSubscriptionR\fsubscription\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12A\n" +
	"\x1daccess_token_refresh_required\x18\x03 \x01(\bR\x1aaccessTokenRefreshRequired\"V\n" +
	"%ResolveMarketplaceRegistrationRequest\x12-\n" +
	"\x12registration_token\x18\x01 \x01(\tR\x11registrationToken\"K\n" +
	"&ResolveMarketplaceRegistrationResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl*\x8d\x01\n" +
	"\rBillingSource\x12\x1e\n" +
	"\x1aBILLING_SOURCE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BILLING_SOURCE_PLATFORM\x10\x01\x12\x1b\n" +
	"\x17BILLING_SOURCE_OPERATOR\x10\x02\x12\"\n" +
	"\x1eBILLING_SOURCE_AWS_MARKETPLACE\x10\x03*\xed\x01\n" +
	"\x11SubscriptionState\x12\"\n" +
	"\x1eSUBSCRIPTION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATE_UNBOUND\x10\x01\x12\x1d\n" +
	"\x19SUBSCRIPTION_STATE_ACTIVE\x10\x02\x12+\n" +
	"'SUBSCRIPTION_STATE_PENDING_VERIFICATION\x10\x03\x12&\n" +
	"\"SUBSCRIPTION_STATE_NEEDS_ATTENTION\x10\x04\x12 \n" +
	"\x1cSUBSCRIPTION_STATE_CANCELLED\x10\x052\xea\x03\n" +
	"\x0eBillingService\x12\x83\x01\n" +
	"\x0fGetBillingState\x12,.jennahapi.billing.v1.GetBillingStateRequest\x1a-.jennahapi.billing.v1.GetBillingStateResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/billing\x12\xb3\x01\n" +
	"\x1bBindMarketplaceRegistration\x128.jennahapi.billing.v1.BindMarketplaceRegistrationRequest\x1a9.jennahapi.billing.v1.BindMarketplaceRegistrationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/billing/aws:bind\x12\x9b\x01\n" +
	"\x1eResolveMarketplaceRegistration\x12;.jennahapi.billing.v1.ResolveMarketplaceRegistrationRequest\x1a<.jennahapi.billing.v1.ResolveMarketplaceRegistrationResponseB+Z)github.com/alphauslabs/jennah-api/billingb\x06proto3"

var (
	file_jennah_billing_v1_billing_proto_rawDescOnce sync.Once
	file_jennah_billing_v1_billing_proto_rawDescData []byte
)

func file_jennah_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_jennah_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_jennah_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jennah_billing_v1_billing_proto_rawDesc), len(file_jennah_billing_v1_billing_proto_rawDesc)))
	})
	return file_jennah_billing_v1_billing_proto_rawDescData
}

var file_jennah_billing_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jennah_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_jennah_billing_v1_billing_proto_goTypes = []any{
	(BillingSource)(0),                             // 0: jennahapi.billing.v1.BillingSource
	(SubscriptionState)(0),                         // 1: jennahapi.billing.v1.SubscriptionState
	(*BoundSubscription)(nil),                      // 2: jennahapi.billing.v1.BoundSubscription
	(*GetBillingStateRequest)(nil),                 // 3: jennahapi.billing.v1.GetBillingStateRequest
	(*GetBillingStateResponse)(nil),                // 4: jennahapi.billing.v1.GetBillingStateResponse
	(*BindMarketplaceRegistrationRequest)(nil),     // 5: jennahapi.billing.v1.BindMarketplaceRegistrationRequest
	(*BindMarketplaceRegistrationResponse)(nil),    // 6: jennahapi.billing.v1.BindMarketplaceRegistrationResponse
	(*ResolveMarketplaceRegistrationRequest)(nil),  // 7: jennahapi.billing.v1.ResolveMarketplaceRegistrationRequest
	(*ResolveMarketplaceRegistrationResponse)(nil), // 8: jennahapi.billing.v1.ResolveMarketplaceRegistrationResponse
	(*timestamppb.Timestamp)(nil),                  // 9: google.protobuf.Timestamp
}
var file_jennah_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: jennahapi.billing.v1.BoundSubscription.source:type_name -> jennahapi.billing.v1.BillingSource
	9, // 1: jennahapi.billing.v1.BoundSubscription.expires_at:type_name -> google.protobuf.Timestamp
	1, // 2: jennahapi.billing.v1.BoundSubscription.state:type_name -> jennahapi.billing.v1.SubscriptionState
	0, // 3: jennahapi.billing.v1.GetBillingStateResponse.source:type_name -> jennahapi.billing.v1.BillingSource
	2, // 4: jennahapi.billing.v1.GetBillingStateResponse.subscriptions:type_name -> jennahapi.billing.v1.BoundSubscription
	2, // 5: jennahapi.billing.v1.BindMarketplaceRegistrationResponse.subscription:type_name -> jennahapi.billing.v1.BoundSubscription
	3, // 6: jennahapi.billing.v1.BillingService.GetBillingState:input_type -> jennahapi.billing.v1.GetBillingStateRequest
	5, // 7: jennahapi.billing.v1.BillingService.BindMarketplaceRegistration:input_type -> jennahapi.billing.v1.BindMarketplaceRegistrationRequest
	7, // 8: jennahapi.billing.v1.BillingService.ResolveMarketplaceRegistration:input_type -> jennahapi.billing.v1.ResolveMarketplaceRegistrationRequest
	4, // 9: jennahapi.billing.v1.BillingService.GetBillingState:output_type -> jennahapi.billing.v1.GetBillingStateResponse
	6, // 10: jennahapi.billing.v1.BillingService.BindMarketplaceRegistration:output_type -> jennahapi.billing.v1.BindMarketplaceRegistrationResponse
	8, // 11: jennahapi.billing.v1.BillingService.ResolveMarketplaceRegistration:output_type -> jennahapi.billing.v1.ResolveMarketplaceRegistrationResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_jennah_billing_v1_billing_proto_init() }
func file_jennah_billing_v1_billing_proto_init() {
	if File_jennah_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jennah_billing_v1_billing_proto_rawDesc), len(file_jennah_billing_v1_billing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jennah_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_jennah_billing_v1_billing_proto_depIdxs,
		EnumInfos:         file_jennah_billing_v1_billing_proto_enumTypes,
		MessageInfos:      file_jennah_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_jennah_billing_v1_billing_proto = out.File
	file_jennah_billing_v1_billing_proto_goTypes = nil
	file_jennah_billing_v1_billing_proto_depIdxs = nil
}
