// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jennah/auth/v1/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_WhoAmI_FullMethodName           = "/jennahapi.auth.v1.AuthService/WhoAmI"
	AuthService_StartLogin_FullMethodName       = "/jennahapi.auth.v1.AuthService/StartLogin"
	AuthService_CompleteLogin_FullMethodName    = "/jennahapi.auth.v1.AuthService/CompleteLogin"
	AuthService_StartDeviceLogin_FullMethodName = "/jennahapi.auth.v1.AuthService/StartDeviceLogin"
	AuthService_PollDeviceLogin_FullMethodName  = "/jennahapi.auth.v1.AuthService/PollDeviceLogin"
	AuthService_RefreshToken_FullMethodName     = "/jennahapi.auth.v1.AuthService/RefreshToken"
	AuthService_Logout_FullMethodName           = "/jennahapi.auth.v1.AuthService/Logout"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auth service definition.
//
// Only WhoAmI is exposed on the grpc-gateway REST surface (it carries a
// google.api.http annotation). Every other RPC here is INTERNAL: it has no
// HTTP annotation, so grpc-gateway emits no route for it and it is reachable
// only over the backend's internal gRPC listener (127.0.0.1:8080), which is
// where jennah-proxy's hand-written /auth/* handlers dial it. Do NOT add a
// google.api.http annotation to the login/device/token RPCs — doing so would
// publish them on the public REST surface.
type AuthServiceClient interface {
	// Gets information about the caller. External (gateway) RPC. Requires a valid
	// jennah access token; returns the resolved caller identity.
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// Begins a browser/authorization-code login. WEB returns the encrypted state
	// blob in the response (proxy stores it in the __Host- cookie); CLI leaves it
	// empty and the backend persists state in the oauth_state Spanner row.
	// Unauthenticated (interceptor allowlist).
	StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error)
	// Completes a login after the provider redirects back to jennah's callback:
	// validates state/PKCE, exchanges the code, verifies the provider identity,
	// upserts the user, and mints jennah tokens. Unauthenticated (allowlist).
	CompleteLogin(ctx context.Context, in *CompleteLoginRequest, opts ...grpc.CallOption) (*CompleteLoginResponse, error)
	// Begins the CLI device-code flow. Unauthenticated (allowlist).
	StartDeviceLogin(ctx context.Context, in *StartDeviceLoginRequest, opts ...grpc.CallOption) (*StartDeviceLoginResponse, error)
	// Polls a pending device-code login for approval. Unauthenticated (allowlist).
	PollDeviceLogin(ctx context.Context, in *PollDeviceLoginRequest, opts ...grpc.CallOption) (*PollDeviceLoginResponse, error)
	// Exchanges an opaque refresh token for a fresh access token. Unauthenticated
	// (the refresh token itself is the credential; allowlist).
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// Revokes the session behind a refresh token. Authenticated.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, AuthService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_StartLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CompleteLogin(ctx context.Context, in *CompleteLoginRequest, opts ...grpc.CallOption) (*CompleteLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_CompleteLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartDeviceLogin(ctx context.Context, in *StartDeviceLoginRequest, opts ...grpc.CallOption) (*StartDeviceLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDeviceLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_StartDeviceLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PollDeviceLogin(ctx context.Context, in *PollDeviceLoginRequest, opts ...grpc.CallOption) (*PollDeviceLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollDeviceLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_PollDeviceLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// Auth service definition.
//
// Only WhoAmI is exposed on the grpc-gateway REST surface (it carries a
// google.api.http annotation). Every other RPC here is INTERNAL: it has no
// HTTP annotation, so grpc-gateway emits no route for it and it is reachable
// only over the backend's internal gRPC listener (127.0.0.1:8080), which is
// where jennah-proxy's hand-written /auth/* handlers dial it. Do NOT add a
// google.api.http annotation to the login/device/token RPCs — doing so would
// publish them on the public REST surface.
type AuthServiceServer interface {
	// Gets information about the caller. External (gateway) RPC. Requires a valid
	// jennah access token; returns the resolved caller identity.
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	// Begins a browser/authorization-code login. WEB returns the encrypted state
	// blob in the response (proxy stores it in the __Host- cookie); CLI leaves it
	// empty and the backend persists state in the oauth_state Spanner row.
	// Unauthenticated (interceptor allowlist).
	StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error)
	// Completes a login after the provider redirects back to jennah's callback:
	// validates state/PKCE, exchanges the code, verifies the provider identity,
	// upserts the user, and mints jennah tokens. Unauthenticated (allowlist).
	CompleteLogin(context.Context, *CompleteLoginRequest) (*CompleteLoginResponse, error)
	// Begins the CLI device-code flow. Unauthenticated (allowlist).
	StartDeviceLogin(context.Context, *StartDeviceLoginRequest) (*StartDeviceLoginResponse, error)
	// Polls a pending device-code login for approval. Unauthenticated (allowlist).
	PollDeviceLogin(context.Context, *PollDeviceLoginRequest) (*PollDeviceLoginResponse, error)
	// Exchanges an opaque refresh token for a fresh access token. Unauthenticated
	// (the refresh token itself is the credential; allowlist).
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// Revokes the session behind a refresh token. Authenticated.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedAuthServiceServer) StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedAuthServiceServer) CompleteLogin(context.Context, *CompleteLoginRequest) (*CompleteLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteLogin not implemented")
}
func (UnimplementedAuthServiceServer) StartDeviceLogin(context.Context, *StartDeviceLoginRequest) (*StartDeviceLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDeviceLogin not implemented")
}
func (UnimplementedAuthServiceServer) PollDeviceLogin(context.Context, *PollDeviceLoginRequest) (*PollDeviceLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollDeviceLogin not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartLogin(ctx, req.(*StartLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CompleteLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CompleteLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CompleteLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CompleteLogin(ctx, req.(*CompleteLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartDeviceLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDeviceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartDeviceLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartDeviceLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartDeviceLogin(ctx, req.(*StartDeviceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PollDeviceLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollDeviceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PollDeviceLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PollDeviceLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PollDeviceLogin(ctx, req.(*PollDeviceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jennahapi.auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhoAmI",
			Handler:    _AuthService_WhoAmI_Handler,
		},
		{
			MethodName: "StartLogin",
			Handler:    _AuthService_StartLogin_Handler,
		},
		{
			MethodName: "CompleteLogin",
			Handler:    _AuthService_CompleteLogin_Handler,
		},
		{
			MethodName: "StartDeviceLogin",
			Handler:    _AuthService_StartDeviceLogin_Handler,
		},
		{
			MethodName: "PollDeviceLogin",
			Handler:    _AuthService_PollDeviceLogin_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jennah/auth/v1/auth.proto",
}
