// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jennah/auth/v1/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_WhoAmI_FullMethodName           = "/jennahapi.auth.v1.AuthService/WhoAmI"
	AuthService_StartLogin_FullMethodName       = "/jennahapi.auth.v1.AuthService/StartLogin"
	AuthService_CompleteLogin_FullMethodName    = "/jennahapi.auth.v1.AuthService/CompleteLogin"
	AuthService_ExchangeCode_FullMethodName     = "/jennahapi.auth.v1.AuthService/ExchangeCode"
	AuthService_StartDeviceLogin_FullMethodName = "/jennahapi.auth.v1.AuthService/StartDeviceLogin"
	AuthService_PollDeviceLogin_FullMethodName  = "/jennahapi.auth.v1.AuthService/PollDeviceLogin"
	AuthService_RefreshToken_FullMethodName     = "/jennahapi.auth.v1.AuthService/RefreshToken"
	AuthService_Logout_FullMethodName           = "/jennahapi.auth.v1.AuthService/Logout"
	AuthService_CreateApiKey_FullMethodName     = "/jennahapi.auth.v1.AuthService/CreateApiKey"
	AuthService_ListApiKeys_FullMethodName      = "/jennahapi.auth.v1.AuthService/ListApiKeys"
	AuthService_RevokeApiKey_FullMethodName     = "/jennahapi.auth.v1.AuthService/RevokeApiKey"
	AuthService_InviteMember_FullMethodName     = "/jennahapi.auth.v1.AuthService/InviteMember"
	AuthService_ListInvitations_FullMethodName  = "/jennahapi.auth.v1.AuthService/ListInvitations"
	AuthService_RevokeInvitation_FullMethodName = "/jennahapi.auth.v1.AuthService/RevokeInvitation"
	AuthService_AcceptInvitation_FullMethodName = "/jennahapi.auth.v1.AuthService/AcceptInvitation"
	AuthService_ListMembers_FullMethodName      = "/jennahapi.auth.v1.AuthService/ListMembers"
	AuthService_ChangeMemberRole_FullMethodName = "/jennahapi.auth.v1.AuthService/ChangeMemberRole"
	AuthService_RemoveMember_FullMethodName     = "/jennahapi.auth.v1.AuthService/RemoveMember"
	AuthService_UpdateEnterprise_FullMethodName = "/jennahapi.auth.v1.AuthService/UpdateEnterprise"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService service definition.
type AuthServiceClient interface {
	// Gets information about the caller. External (gateway) RPC. Requires a valid
	// jennah access token; returns the resolved caller identity.
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// Begins a browser/authorization-code login. WEB returns the encrypted state
	// blob in the response (proxy stores it in the __Host- cookie); CLI leaves it
	// empty and the backend persists state in the oauth_state Spanner row.
	// Unauthenticated (interceptor allowlist).
	StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error)
	// Completes a login after the provider redirects back to jennah's callback:
	// validates state/PKCE, exchanges the code, verifies the provider identity,
	// upserts the user, and mints jennah tokens. Unauthenticated (allowlist).
	CompleteLogin(ctx context.Context, in *CompleteLoginRequest, opts ...grpc.CallOption) (*CompleteLoginResponse, error)
	// Redeems a single-use one-time code (issued by CompleteLogin in CODE
	// response mode) for the minted jennah tokens. Used by a confidential
	// server-side client (a BFF) so tokens are never delivered to the browser.
	// The code is single-use and short-lived. Unauthenticated (the code itself
	// is the credential; allowlist).
	ExchangeCode(ctx context.Context, in *ExchangeCodeRequest, opts ...grpc.CallOption) (*ExchangeCodeResponse, error)
	// Begins the CLI device-code flow. Unauthenticated (allowlist).
	StartDeviceLogin(ctx context.Context, in *StartDeviceLoginRequest, opts ...grpc.CallOption) (*StartDeviceLoginResponse, error)
	// Polls a pending device-code login for approval. Unauthenticated (allowlist).
	PollDeviceLogin(ctx context.Context, in *PollDeviceLoginRequest, opts ...grpc.CallOption) (*PollDeviceLoginResponse, error)
	// Exchanges an opaque refresh token for a fresh access token. Unauthenticated
	// (the refresh token itself is the credential; allowlist).
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// Revokes the session behind a refresh token. Authenticated.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Mints a new API key for the caller's active enterprise. External (gateway)
	// RPC. Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN, resolved live from the
	// Memberships table (never trusted from a claim). The plaintext secret is
	// returned exactly once, in this response, and is NOT retrievable afterward —
	// only its sha256 hash is stored. The key resolves to a ROLE_MEMBER-equivalent
	// service principal scoped to the enterprise.
	CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*CreateApiKeyResponse, error)
	// Lists the caller enterprise's API keys as non-secret metadata only (never
	// the secret or its hash), most-recent first, with page_size/page_token
	// pagination. External (gateway) RPC. Authenticated; scoped to the token's
	// active enterprise.
	ListApiKeys(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error)
	// Revokes an API key the caller's enterprise owns, taking effect on the next
	// request (validation is a per-request lookup, so there is no TTL lag).
	// External (gateway) RPC, modeled as a custom method (POST ...:revoke) rather
	// than DELETE because it does not remove the resource — the row is retained
	// with RevokedAt set, so the key stays listable as revoked. Authenticated AND
	// gated to ROLE_ROOT/ROLE_ADMIN. A key_id not owned by the caller's active
	// enterprise is treated as not found.
	RevokeApiKey(ctx context.Context, in *RevokeApiKeyRequest, opts ...grpc.CallOption) (*RevokeApiKeyResponse, error)
	// Invites a person by email into the caller's active enterprise, granting
	// ROLE_ADMIN or ROLE_MEMBER (never ROLE_ROOT). External (gateway) RPC.
	// Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN (resolved live from the
	// Memberships table). Membership is NOT granted by email match: this only
	// creates a pending invitation bound to a single-use token, returned exactly
	// once in the response for the inviter to share — the grant happens when the
	// invitee accepts (AcceptInvitation) while signed in. Rejects an email already
	// a member and a second pending invite for the same email.
	InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error)
	// Lists the caller enterprise's pending invitations as non-secret metadata
	// (never any token value), most-recent first. External (gateway) RPC.
	// Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN.
	ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error)
	// Revokes a pending invitation so its token can never be accepted. Modeled as
	// a custom method (POST ...:revoke) rather than DELETE because the row is
	// retained with status INVITATION_STATUS_REVOKED, so it stays listable.
	// External (gateway) RPC. Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN. An
	// invitation_id not in the caller's active enterprise is treated as not found.
	RevokeInvitation(ctx context.Context, in *RevokeInvitationRequest, opts ...grpc.CallOption) (*RevokeInvitationResponse, error)
	// Accepts an invitation, granting the authenticated caller membership in the
	// invitation's enterprise with the invited role. External (gateway) RPC.
	// Authenticated as ANY caller: the target enterprise comes from the invitation
	// (not the caller's token), the single-use token is the capability, and the
	// caller's email need NOT match the invitation's. Already-a-member is a no-op
	// success. The caller's current access token stays scoped to their previous
	// enterprise; to operate in the newly joined one they call RefreshToken with
	// enterprise_id set.
	AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*AcceptInvitationResponse, error)
	// Lists the members of the caller's active enterprise (user id, email, role,
	// join time), oldest first. External (gateway) RPC. Authenticated; visible to
	// any member (a team roster is not sensitive within the enterprise).
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	// Changes a member's role to ROLE_ADMIN or ROLE_MEMBER within the caller's
	// active enterprise. External (gateway) RPC. Authenticated AND gated to
	// ROLE_ROOT/ROLE_ADMIN. The enterprise's ROLE_ROOT cannot be changed and
	// ROLE_ROOT is never grantable.
	ChangeMemberRole(ctx context.Context, in *ChangeMemberRoleRequest, opts ...grpc.CallOption) (*ChangeMemberRoleResponse, error)
	// Removes a member from the caller's active enterprise, deleting their
	// Memberships row and revoking their refresh sessions scoped to it (so no new
	// access token can be minted for it; an already-issued one lasts until it
	// expires). External (gateway) RPC. Authenticated AND gated to
	// ROLE_ROOT/ROLE_ADMIN (a member MAY remove themselves — leave). The
	// enterprise's ROLE_ROOT cannot be removed. A user_id not in the caller's
	// active enterprise is treated as not found.
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	// Updates mutable fields of the caller's active enterprise (currently just its
	// display name). External (gateway) RPC. Authenticated AND gated to
	// ROLE_ROOT/ROLE_ADMIN (resolved live from the Memberships table). The target
	// is always the caller's active enterprise (from the token), never a path/body
	// id, mirroring ListMembers/ChangeMemberRole.
	UpdateEnterprise(ctx context.Context, in *UpdateEnterpriseRequest, opts ...grpc.CallOption) (*UpdateEnterpriseResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, AuthService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_StartLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CompleteLogin(ctx context.Context, in *CompleteLoginRequest, opts ...grpc.CallOption) (*CompleteLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_CompleteLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ExchangeCode(ctx context.Context, in *ExchangeCodeRequest, opts ...grpc.CallOption) (*ExchangeCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeCodeResponse)
	err := c.cc.Invoke(ctx, AuthService_ExchangeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartDeviceLogin(ctx context.Context, in *StartDeviceLoginRequest, opts ...grpc.CallOption) (*StartDeviceLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDeviceLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_StartDeviceLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PollDeviceLogin(ctx context.Context, in *PollDeviceLoginRequest, opts ...grpc.CallOption) (*PollDeviceLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollDeviceLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_PollDeviceLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*CreateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApiKeyResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListApiKeys(ctx context.Context, in *ListApiKeysRequest, opts ...grpc.CallOption) (*ListApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApiKeysResponse)
	err := c.cc.Invoke(ctx, AuthService_ListApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeApiKey(ctx context.Context, in *RevokeApiKeyRequest, opts ...grpc.CallOption) (*RevokeApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeApiKeyResponse)
	err := c.cc.Invoke(ctx, AuthService_RevokeApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...grpc.CallOption) (*InviteMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMemberResponse)
	err := c.cc.Invoke(ctx, AuthService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvitationsResponse)
	err := c.cc.Invoke(ctx, AuthService_ListInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeInvitation(ctx context.Context, in *RevokeInvitationRequest, opts ...grpc.CallOption) (*RevokeInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeInvitationResponse)
	err := c.cc.Invoke(ctx, AuthService_RevokeInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AcceptInvitation(ctx context.Context, in *AcceptInvitationRequest, opts ...grpc.CallOption) (*AcceptInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptInvitationResponse)
	err := c.cc.Invoke(ctx, AuthService_AcceptInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, AuthService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangeMemberRole(ctx context.Context, in *ChangeMemberRoleRequest, opts ...grpc.CallOption) (*ChangeMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeMemberRoleResponse)
	err := c.cc.Invoke(ctx, AuthService_ChangeMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, AuthService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateEnterprise(ctx context.Context, in *UpdateEnterpriseRequest, opts ...grpc.CallOption) (*UpdateEnterpriseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnterpriseResponse)
	err := c.cc.Invoke(ctx, AuthService_UpdateEnterprise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService service definition.
type AuthServiceServer interface {
	// Gets information about the caller. External (gateway) RPC. Requires a valid
	// jennah access token; returns the resolved caller identity.
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	// Begins a browser/authorization-code login. WEB returns the encrypted state
	// blob in the response (proxy stores it in the __Host- cookie); CLI leaves it
	// empty and the backend persists state in the oauth_state Spanner row.
	// Unauthenticated (interceptor allowlist).
	StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error)
	// Completes a login after the provider redirects back to jennah's callback:
	// validates state/PKCE, exchanges the code, verifies the provider identity,
	// upserts the user, and mints jennah tokens. Unauthenticated (allowlist).
	CompleteLogin(context.Context, *CompleteLoginRequest) (*CompleteLoginResponse, error)
	// Redeems a single-use one-time code (issued by CompleteLogin in CODE
	// response mode) for the minted jennah tokens. Used by a confidential
	// server-side client (a BFF) so tokens are never delivered to the browser.
	// The code is single-use and short-lived. Unauthenticated (the code itself
	// is the credential; allowlist).
	ExchangeCode(context.Context, *ExchangeCodeRequest) (*ExchangeCodeResponse, error)
	// Begins the CLI device-code flow. Unauthenticated (allowlist).
	StartDeviceLogin(context.Context, *StartDeviceLoginRequest) (*StartDeviceLoginResponse, error)
	// Polls a pending device-code login for approval. Unauthenticated (allowlist).
	PollDeviceLogin(context.Context, *PollDeviceLoginRequest) (*PollDeviceLoginResponse, error)
	// Exchanges an opaque refresh token for a fresh access token. Unauthenticated
	// (the refresh token itself is the credential; allowlist).
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// Revokes the session behind a refresh token. Authenticated.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Mints a new API key for the caller's active enterprise. External (gateway)
	// RPC. Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN, resolved live from the
	// Memberships table (never trusted from a claim). The plaintext secret is
	// returned exactly once, in this response, and is NOT retrievable afterward —
	// only its sha256 hash is stored. The key resolves to a ROLE_MEMBER-equivalent
	// service principal scoped to the enterprise.
	CreateApiKey(context.Context, *CreateApiKeyRequest) (*CreateApiKeyResponse, error)
	// Lists the caller enterprise's API keys as non-secret metadata only (never
	// the secret or its hash), most-recent first, with page_size/page_token
	// pagination. External (gateway) RPC. Authenticated; scoped to the token's
	// active enterprise.
	ListApiKeys(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error)
	// Revokes an API key the caller's enterprise owns, taking effect on the next
	// request (validation is a per-request lookup, so there is no TTL lag).
	// External (gateway) RPC, modeled as a custom method (POST ...:revoke) rather
	// than DELETE because it does not remove the resource — the row is retained
	// with RevokedAt set, so the key stays listable as revoked. Authenticated AND
	// gated to ROLE_ROOT/ROLE_ADMIN. A key_id not owned by the caller's active
	// enterprise is treated as not found.
	RevokeApiKey(context.Context, *RevokeApiKeyRequest) (*RevokeApiKeyResponse, error)
	// Invites a person by email into the caller's active enterprise, granting
	// ROLE_ADMIN or ROLE_MEMBER (never ROLE_ROOT). External (gateway) RPC.
	// Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN (resolved live from the
	// Memberships table). Membership is NOT granted by email match: this only
	// creates a pending invitation bound to a single-use token, returned exactly
	// once in the response for the inviter to share — the grant happens when the
	// invitee accepts (AcceptInvitation) while signed in. Rejects an email already
	// a member and a second pending invite for the same email.
	InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error)
	// Lists the caller enterprise's pending invitations as non-secret metadata
	// (never any token value), most-recent first. External (gateway) RPC.
	// Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN.
	ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error)
	// Revokes a pending invitation so its token can never be accepted. Modeled as
	// a custom method (POST ...:revoke) rather than DELETE because the row is
	// retained with status INVITATION_STATUS_REVOKED, so it stays listable.
	// External (gateway) RPC. Authenticated AND gated to ROLE_ROOT/ROLE_ADMIN. An
	// invitation_id not in the caller's active enterprise is treated as not found.
	RevokeInvitation(context.Context, *RevokeInvitationRequest) (*RevokeInvitationResponse, error)
	// Accepts an invitation, granting the authenticated caller membership in the
	// invitation's enterprise with the invited role. External (gateway) RPC.
	// Authenticated as ANY caller: the target enterprise comes from the invitation
	// (not the caller's token), the single-use token is the capability, and the
	// caller's email need NOT match the invitation's. Already-a-member is a no-op
	// success. The caller's current access token stays scoped to their previous
	// enterprise; to operate in the newly joined one they call RefreshToken with
	// enterprise_id set.
	AcceptInvitation(context.Context, *AcceptInvitationRequest) (*AcceptInvitationResponse, error)
	// Lists the members of the caller's active enterprise (user id, email, role,
	// join time), oldest first. External (gateway) RPC. Authenticated; visible to
	// any member (a team roster is not sensitive within the enterprise).
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	// Changes a member's role to ROLE_ADMIN or ROLE_MEMBER within the caller's
	// active enterprise. External (gateway) RPC. Authenticated AND gated to
	// ROLE_ROOT/ROLE_ADMIN. The enterprise's ROLE_ROOT cannot be changed and
	// ROLE_ROOT is never grantable.
	ChangeMemberRole(context.Context, *ChangeMemberRoleRequest) (*ChangeMemberRoleResponse, error)
	// Removes a member from the caller's active enterprise, deleting their
	// Memberships row and revoking their refresh sessions scoped to it (so no new
	// access token can be minted for it; an already-issued one lasts until it
	// expires). External (gateway) RPC. Authenticated AND gated to
	// ROLE_ROOT/ROLE_ADMIN (a member MAY remove themselves — leave). The
	// enterprise's ROLE_ROOT cannot be removed. A user_id not in the caller's
	// active enterprise is treated as not found.
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	// Updates mutable fields of the caller's active enterprise (currently just its
	// display name). External (gateway) RPC. Authenticated AND gated to
	// ROLE_ROOT/ROLE_ADMIN (resolved live from the Memberships table). The target
	// is always the caller's active enterprise (from the token), never a path/body
	// id, mirroring ListMembers/ChangeMemberRole.
	UpdateEnterprise(context.Context, *UpdateEnterpriseRequest) (*UpdateEnterpriseResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedAuthServiceServer) StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedAuthServiceServer) CompleteLogin(context.Context, *CompleteLoginRequest) (*CompleteLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteLogin not implemented")
}
func (UnimplementedAuthServiceServer) ExchangeCode(context.Context, *ExchangeCodeRequest) (*ExchangeCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeCode not implemented")
}
func (UnimplementedAuthServiceServer) StartDeviceLogin(context.Context, *StartDeviceLoginRequest) (*StartDeviceLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDeviceLogin not implemented")
}
func (UnimplementedAuthServiceServer) PollDeviceLogin(context.Context, *PollDeviceLoginRequest) (*PollDeviceLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollDeviceLogin not implemented")
}
func (UnimplementedAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) CreateApiKey(context.Context, *CreateApiKeyRequest) (*CreateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApiKey not implemented")
}
func (UnimplementedAuthServiceServer) ListApiKeys(context.Context, *ListApiKeysRequest) (*ListApiKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApiKeys not implemented")
}
func (UnimplementedAuthServiceServer) RevokeApiKey(context.Context, *RevokeApiKeyRequest) (*RevokeApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeApiKey not implemented")
}
func (UnimplementedAuthServiceServer) InviteMember(context.Context, *InviteMemberRequest) (*InviteMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedAuthServiceServer) ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvitations not implemented")
}
func (UnimplementedAuthServiceServer) RevokeInvitation(context.Context, *RevokeInvitationRequest) (*RevokeInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeInvitation not implemented")
}
func (UnimplementedAuthServiceServer) AcceptInvitation(context.Context, *AcceptInvitationRequest) (*AcceptInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptInvitation not implemented")
}
func (UnimplementedAuthServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedAuthServiceServer) ChangeMemberRole(context.Context, *ChangeMemberRoleRequest) (*ChangeMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMemberRole not implemented")
}
func (UnimplementedAuthServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedAuthServiceServer) UpdateEnterprise(context.Context, *UpdateEnterpriseRequest) (*UpdateEnterpriseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnterprise not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartLogin(ctx, req.(*StartLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CompleteLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CompleteLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CompleteLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CompleteLogin(ctx, req.(*CompleteLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ExchangeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ExchangeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ExchangeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ExchangeCode(ctx, req.(*ExchangeCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartDeviceLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDeviceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartDeviceLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartDeviceLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartDeviceLogin(ctx, req.(*StartDeviceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PollDeviceLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollDeviceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PollDeviceLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PollDeviceLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PollDeviceLogin(ctx, req.(*PollDeviceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateApiKey(ctx, req.(*CreateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListApiKeys(ctx, req.(*ListApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokeApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeApiKey(ctx, req.(*RevokeApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InviteMember(ctx, req.(*InviteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListInvitations(ctx, req.(*ListInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokeInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeInvitation(ctx, req.(*RevokeInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_AcceptInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AcceptInvitation(ctx, req.(*AcceptInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangeMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangeMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChangeMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangeMemberRole(ctx, req.(*ChangeMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnterpriseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateEnterprise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateEnterprise(ctx, req.(*UpdateEnterpriseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jennahapi.auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhoAmI",
			Handler:    _AuthService_WhoAmI_Handler,
		},
		{
			MethodName: "StartLogin",
			Handler:    _AuthService_StartLogin_Handler,
		},
		{
			MethodName: "CompleteLogin",
			Handler:    _AuthService_CompleteLogin_Handler,
		},
		{
			MethodName: "ExchangeCode",
			Handler:    _AuthService_ExchangeCode_Handler,
		},
		{
			MethodName: "StartDeviceLogin",
			Handler:    _AuthService_StartDeviceLogin_Handler,
		},
		{
			MethodName: "PollDeviceLogin",
			Handler:    _AuthService_PollDeviceLogin_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
		{
			MethodName: "CreateApiKey",
			Handler:    _AuthService_CreateApiKey_Handler,
		},
		{
			MethodName: "ListApiKeys",
			Handler:    _AuthService_ListApiKeys_Handler,
		},
		{
			MethodName: "RevokeApiKey",
			Handler:    _AuthService_RevokeApiKey_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _AuthService_InviteMember_Handler,
		},
		{
			MethodName: "ListInvitations",
			Handler:    _AuthService_ListInvitations_Handler,
		},
		{
			MethodName: "RevokeInvitation",
			Handler:    _AuthService_RevokeInvitation_Handler,
		},
		{
			MethodName: "AcceptInvitation",
			Handler:    _AuthService_AcceptInvitation_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _AuthService_ListMembers_Handler,
		},
		{
			MethodName: "ChangeMemberRole",
			Handler:    _AuthService_ChangeMemberRole_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _AuthService_RemoveMember_Handler,
		},
		{
			MethodName: "UpdateEnterprise",
			Handler:    _AuthService_UpdateEnterprise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jennah/auth/v1/auth.proto",
}
