// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jennah/auth/v1/auth.proto

package auth

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity provider jennah supports for social login.
type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_GOOGLE      Provider = 1
	Provider_PROVIDER_GITHUB      Provider = 2
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_GOOGLE",
		2: "PROVIDER_GITHUB",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_GOOGLE":      1,
		"PROVIDER_GITHUB":      2,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_jennah_auth_v1_auth_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

// Client class initiating a login; selects the flow and where flow state lives.
type ClientType int32

const (
	ClientType_CLIENT_TYPE_UNSPECIFIED ClientType = 0
	// Web frontend: authorization-code + PKCE, state carried in a __Host- cookie.
	ClientType_CLIENT_TYPE_WEB ClientType = 1
	// CLI: loopback / device-code, state persisted in the oauth_state table.
	ClientType_CLIENT_TYPE_CLI ClientType = 2
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "CLIENT_TYPE_UNSPECIFIED",
		1: "CLIENT_TYPE_WEB",
		2: "CLIENT_TYPE_CLI",
	}
	ClientType_value = map[string]int32{
		"CLIENT_TYPE_UNSPECIFIED": 0,
		"CLIENT_TYPE_WEB":         1,
		"CLIENT_TYPE_CLI":         2,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_auth_v1_auth_proto_enumTypes[1].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_jennah_auth_v1_auth_proto_enumTypes[1]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

// How minted jennah tokens are delivered on the final redirect to the app's
// app_redirect. Chosen at StartLogin and carried inside the encrypted state so
// the callback resolves it without per-instance memory.
type ResponseMode int32

const (
	// Defaults to FRAGMENT.
	ResponseMode_RESPONSE_MODE_UNSPECIFIED ResponseMode = 0
	// Public client / test harness: callback redirects with tokens in the URL
	// fragment (#access_token=...). NOT for production — the refresh token
	// transits the browser.
	ResponseMode_RESPONSE_MODE_FRAGMENT ResponseMode = 1
	// Confidential client (server-side BFF): callback redirects with only a
	// single-use ?code=...; the client redeems it via ExchangeCode. No jennah
	// token ever reaches the browser.
	ResponseMode_RESPONSE_MODE_CODE ResponseMode = 2
)

// Enum value maps for ResponseMode.
var (
	ResponseMode_name = map[int32]string{
		0: "RESPONSE_MODE_UNSPECIFIED",
		1: "RESPONSE_MODE_FRAGMENT",
		2: "RESPONSE_MODE_CODE",
	}
	ResponseMode_value = map[string]int32{
		"RESPONSE_MODE_UNSPECIFIED": 0,
		"RESPONSE_MODE_FRAGMENT":    1,
		"RESPONSE_MODE_CODE":        2,
	}
)

func (x ResponseMode) Enum() *ResponseMode {
	p := new(ResponseMode)
	*p = x
	return p
}

func (x ResponseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_auth_v1_auth_proto_enumTypes[2].Descriptor()
}

func (ResponseMode) Type() protoreflect.EnumType {
	return &file_jennah_auth_v1_auth_proto_enumTypes[2]
}

func (x ResponseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseMode.Descriptor instead.
func (ResponseMode) EnumDescriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

// A caller's role within an enterprise. Exactly one ROLE_ROOT per enterprise
// (its creator/owner); resolved from the Memberships table, never carried in
// the access token (so role changes apply immediately).
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_ROOT        Role = 1 // creator/owner, exactly one per enterprise
	Role_ROLE_ADMIN       Role = 2
	Role_ROLE_MEMBER      Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ROOT",
		2: "ROLE_ADMIN",
		3: "ROLE_MEMBER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_ROOT":        1,
		"ROLE_ADMIN":       2,
		"ROLE_MEMBER":      3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_auth_v1_auth_proto_enumTypes[3].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_jennah_auth_v1_auth_proto_enumTypes[3]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

// Approval state of a device-code login. STATUS_PENDING means keep polling;
// tokens/identity are populated only on STATUS_APPROVED.
type PollDeviceLoginResponse_Status int32

const (
	PollDeviceLoginResponse_STATUS_UNSPECIFIED PollDeviceLoginResponse_Status = 0
	PollDeviceLoginResponse_STATUS_PENDING     PollDeviceLoginResponse_Status = 1
	PollDeviceLoginResponse_STATUS_APPROVED    PollDeviceLoginResponse_Status = 2
	PollDeviceLoginResponse_STATUS_DENIED      PollDeviceLoginResponse_Status = 3
	PollDeviceLoginResponse_STATUS_EXPIRED     PollDeviceLoginResponse_Status = 4
)

// Enum value maps for PollDeviceLoginResponse_Status.
var (
	PollDeviceLoginResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_APPROVED",
		3: "STATUS_DENIED",
		4: "STATUS_EXPIRED",
	}
	PollDeviceLoginResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_APPROVED":    2,
		"STATUS_DENIED":      3,
		"STATUS_EXPIRED":     4,
	}
)

func (x PollDeviceLoginResponse_Status) Enum() *PollDeviceLoginResponse_Status {
	p := new(PollDeviceLoginResponse_Status)
	*p = x
	return p
}

func (x PollDeviceLoginResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PollDeviceLoginResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_jennah_auth_v1_auth_proto_enumTypes[4].Descriptor()
}

func (PollDeviceLoginResponse_Status) Type() protoreflect.EnumType {
	return &file_jennah_auth_v1_auth_proto_enumTypes[4]
}

func (x PollDeviceLoginResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PollDeviceLoginResponse_Status.Descriptor instead.
func (PollDeviceLoginResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{14, 0}
}

// One of the caller's enterprise memberships (a row in the Memberships join
// table), surfaced in Identity so a multi-enterprise user can pick which one to
// switch into.
type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnterpriseId  string                 `protobuf:"bytes,1,opt,name=enterprise_id,json=enterpriseId,proto3" json:"enterprise_id,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=jennahapi.auth.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetEnterpriseId() string {
	if x != nil {
		return x.EnterpriseId
	}
	return ""
}

func (x *Membership) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

// The resolved jennah caller identity. jennah's own user id is authoritative;
// provider_uid/email come from the provider that established the session.
type Identity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // jennah's internal user id (not the provider uid)
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified   bool                   `protobuf:"varint,3,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Picture         string                 `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	Provider        Provider               `protobuf:"varint,6,opt,name=provider,proto3,enum=jennahapi.auth.v1.Provider" json:"provider,omitempty"` // provider that established THIS session
	LinkedProviders []Provider             `protobuf:"varint,7,rep,packed,name=linked_providers,json=linkedProviders,proto3,enum=jennahapi.auth.v1.Provider" json:"linked_providers,omitempty"`
	// Enterprise scope. active_enterprise_id is the enterprise the current access
	// token is scoped to (the `enterprise_id` JWT claim); memberships lists every
	// enterprise the caller belongs to, for enterprise switching in the UI.
	ActiveEnterpriseId string        `protobuf:"bytes,8,opt,name=active_enterprise_id,json=activeEnterpriseId,proto3" json:"active_enterprise_id,omitempty"`
	Memberships        []*Membership `protobuf:"bytes,9,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Identity) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Identity) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *Identity) GetLinkedProviders() []Provider {
	if x != nil {
		return x.LinkedProviders
	}
	return nil
}

func (x *Identity) GetActiveEnterpriseId() string {
	if x != nil {
		return x.ActiveEnterpriseId
	}
	return ""
}

func (x *Identity) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

// Entitlement is the caller's current tier and trial state for the active
// enterprise, mirrored from the access token so a client can render account
// status (a trial countdown, an upgrade prompt) without decoding the JWT. Only
// the trial gate is enforced today; tier is a free-form string (e.g. "trial")
// while paid tiers are still being defined.
type Entitlement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tier  string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"` // e.g. "trial"
	// trial_ends_at is the immutable trial deadline; unset when the caller is not
	// on a trial or has no known deadline.
	TrialEndsAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=trial_ends_at,json=trialEndsAt,proto3" json:"trial_ends_at,omitempty"`
	// trial_active is the server's decision: true while the trial is still valid
	// (or the tier is not a trial), false once it has lapsed. A caller whose
	// trial has lapsed is blocked from other RPCs, so this is chiefly meaningful
	// because WhoAmI remains callable to surface exactly this state.
	TrialActive   bool `protobuf:"varint,3,opt,name=trial_active,json=trialActive,proto3" json:"trial_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entitlement) Reset() {
	*x = Entitlement{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entitlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entitlement) ProtoMessage() {}

func (x *Entitlement) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entitlement.ProtoReflect.Descriptor instead.
func (*Entitlement) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Entitlement) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Entitlement) GetTrialEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrialEndsAt
	}
	return nil
}

func (x *Entitlement) GetTrialActive() bool {
	if x != nil {
		return x.TrialActive
	}
	return false
}

// Request message for the AuthService.WhoAmI rpc.
type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

// Response message for the AuthService.WhoAmI rpc.
type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Identity              `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Entitlement   *Entitlement           `protobuf:"bytes,2,opt,name=entitlement,proto3" json:"entitlement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *WhoAmIResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *WhoAmIResponse) GetEntitlement() *Entitlement {
	if x != nil {
		return x.Entitlement
	}
	return nil
}

// Request message for the AuthService.StartLogin rpc.
type StartLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=jennahapi.auth.v1.Provider" json:"provider,omitempty"`
	ClientType    ClientType             `protobuf:"varint,2,opt,name=client_type,json=clientType,proto3,enum=jennahapi.auth.v1.ClientType" json:"client_type,omitempty"`
	AppRedirect   string                 `protobuf:"bytes,3,opt,name=app_redirect,json=appRedirect,proto3" json:"app_redirect,omitempty"`                                         // where to send the browser after login; validated vs allowlist
	ResponseMode  ResponseMode           `protobuf:"varint,4,opt,name=response_mode,json=responseMode,proto3,enum=jennahapi.auth.v1.ResponseMode" json:"response_mode,omitempty"` // token delivery on the final redirect; defaults to FRAGMENT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoginRequest) Reset() {
	*x = StartLoginRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginRequest) ProtoMessage() {}

func (x *StartLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginRequest.ProtoReflect.Descriptor instead.
func (*StartLoginRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *StartLoginRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *StartLoginRequest) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_CLIENT_TYPE_UNSPECIFIED
}

func (x *StartLoginRequest) GetAppRedirect() string {
	if x != nil {
		return x.AppRedirect
	}
	return ""
}

func (x *StartLoginRequest) GetResponseMode() ResponseMode {
	if x != nil {
		return x.ResponseMode
	}
	return ResponseMode_RESPONSE_MODE_UNSPECIFIED
}

// Response message for the AuthService.StartLogin rpc.
type StartLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorizeUrl  string                 `protobuf:"bytes,1,opt,name=authorize_url,json=authorizeUrl,proto3" json:"authorize_url,omitempty"` // proxy 302s the browser here
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                                   // WEB: encrypted state blob for the __Host- cookie; CLI: empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoginResponse) Reset() {
	*x = StartLoginResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoginResponse) ProtoMessage() {}

func (x *StartLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoginResponse.ProtoReflect.Descriptor instead.
func (*StartLoginResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *StartLoginResponse) GetAuthorizeUrl() string {
	if x != nil {
		return x.AuthorizeUrl
	}
	return ""
}

func (x *StartLoginResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// Request message for the AuthService.CompleteLogin rpc.
type CompleteLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=jennahapi.auth.v1.Provider" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                        // provider auth code from the callback query
	CallbackState string                 `protobuf:"bytes,3,opt,name=callback_state,json=callbackState,proto3" json:"callback_state,omitempty"` // `state` query param (CSRF match / oauth_state key)
	CookieState   string                 `protobuf:"bytes,4,opt,name=cookie_state,json=cookieState,proto3" json:"cookie_state,omitempty"`       // WEB: encrypted blob read back from the __Host- cookie; CLI: empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteLoginRequest) Reset() {
	*x = CompleteLoginRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLoginRequest) ProtoMessage() {}

func (x *CompleteLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLoginRequest.ProtoReflect.Descriptor instead.
func (*CompleteLoginRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteLoginRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *CompleteLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteLoginRequest) GetCallbackState() string {
	if x != nil {
		return x.CallbackState
	}
	return ""
}

func (x *CompleteLoginRequest) GetCookieState() string {
	if x != nil {
		return x.CookieState
	}
	return ""
}

// Response message for the AuthService.CompleteLogin rpc.
//
// Delivery depends on response_mode. In FRAGMENT mode the token fields are
// populated and the proxy puts them in the redirect fragment. In CODE mode the
// tokens are withheld from this response and `code` carries the single-use
// one-time code the proxy places on the redirect (?code=...) for a confidential
// client to redeem via ExchangeCode.
type CompleteLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // FRAGMENT mode only: jennah JWT (~1h)
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // FRAGMENT mode only: opaque, revocable (~30d)
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`         // access-token TTL, seconds
	AppRedirect   string                 `protobuf:"bytes,4,opt,name=app_redirect,json=appRedirect,proto3" json:"app_redirect,omitempty"`    // validated target the proxy redirects the browser to
	Identity      *Identity              `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`                                                                          // CODE mode only: single-use one-time code for the redirect
	ResponseMode  ResponseMode           `protobuf:"varint,7,opt,name=response_mode,json=responseMode,proto3,enum=jennahapi.auth.v1.ResponseMode" json:"response_mode,omitempty"` // resolved delivery mode; tells the proxy how to deliver
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteLoginResponse) Reset() {
	*x = CompleteLoginResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLoginResponse) ProtoMessage() {}

func (x *CompleteLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLoginResponse.ProtoReflect.Descriptor instead.
func (*CompleteLoginResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CompleteLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CompleteLoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *CompleteLoginResponse) GetAppRedirect() string {
	if x != nil {
		return x.AppRedirect
	}
	return ""
}

func (x *CompleteLoginResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *CompleteLoginResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteLoginResponse) GetResponseMode() ResponseMode {
	if x != nil {
		return x.ResponseMode
	}
	return ResponseMode_RESPONSE_MODE_UNSPECIFIED
}

// Request message for the AuthService.ExchangeCode rpc.
type ExchangeCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // the single-use one-time code from a CODE-mode callback
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCodeRequest) Reset() {
	*x = ExchangeCodeRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCodeRequest) ProtoMessage() {}

func (x *ExchangeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCodeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeCodeRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ExchangeCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Response message for the AuthService.ExchangeCode rpc.
type ExchangeCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`    // jennah JWT (~1h)
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // opaque, revocable (~30d)
	TokenType     string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`          // "Bearer"
	ExpiresIn     int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`         // access-token TTL, seconds
	IsNewUser     bool                   `protobuf:"varint,5,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`       // true when this login was a first-time signup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeCodeResponse) Reset() {
	*x = ExchangeCodeResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeCodeResponse) ProtoMessage() {}

func (x *ExchangeCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeCodeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeCodeResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ExchangeCodeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeCodeResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ExchangeCodeResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ExchangeCodeResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *ExchangeCodeResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

// Request message for the AuthService.StartDeviceLogin rpc.
type StartDeviceLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=jennahapi.auth.v1.Provider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDeviceLoginRequest) Reset() {
	*x = StartDeviceLoginRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeviceLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeviceLoginRequest) ProtoMessage() {}

func (x *StartDeviceLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeviceLoginRequest.ProtoReflect.Descriptor instead.
func (*StartDeviceLoginRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *StartDeviceLoginRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

// Response message for the AuthService.StartDeviceLogin rpc.
type StartDeviceLoginResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode              string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"` // secret; CLI polls with this
	UserCode                string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`       // shown to the user
	VerificationUri         string                 `protobuf:"bytes,3,opt,name=verification_uri,json=verificationUri,proto3" json:"verification_uri,omitempty"`
	VerificationUriComplete string                 `protobuf:"bytes,4,opt,name=verification_uri_complete,json=verificationUriComplete,proto3" json:"verification_uri_complete,omitempty"`
	Interval                int64                  `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"` // minimum poll interval, seconds
	ExpiresIn               int64                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StartDeviceLoginResponse) Reset() {
	*x = StartDeviceLoginResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeviceLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeviceLoginResponse) ProtoMessage() {}

func (x *StartDeviceLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeviceLoginResponse.ProtoReflect.Descriptor instead.
func (*StartDeviceLoginResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *StartDeviceLoginResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *StartDeviceLoginResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *StartDeviceLoginResponse) GetVerificationUri() string {
	if x != nil {
		return x.VerificationUri
	}
	return ""
}

func (x *StartDeviceLoginResponse) GetVerificationUriComplete() string {
	if x != nil {
		return x.VerificationUriComplete
	}
	return ""
}

func (x *StartDeviceLoginResponse) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *StartDeviceLoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// Request message for the AuthService.PollDeviceLogin rpc.
type PollDeviceLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode    string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDeviceLoginRequest) Reset() {
	*x = PollDeviceLoginRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDeviceLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDeviceLoginRequest) ProtoMessage() {}

func (x *PollDeviceLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDeviceLoginRequest.ProtoReflect.Descriptor instead.
func (*PollDeviceLoginRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *PollDeviceLoginRequest) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

// Response message for the AuthService.PollDeviceLogin rpc.
type PollDeviceLoginResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Status        PollDeviceLoginResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=jennahapi.auth.v1.PollDeviceLoginResponse_Status" json:"status,omitempty"`
	AccessToken   string                         `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                         `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                          `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Identity      *Identity                      `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollDeviceLoginResponse) Reset() {
	*x = PollDeviceLoginResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollDeviceLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollDeviceLoginResponse) ProtoMessage() {}

func (x *PollDeviceLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollDeviceLoginResponse.ProtoReflect.Descriptor instead.
func (*PollDeviceLoginResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *PollDeviceLoginResponse) GetStatus() PollDeviceLoginResponse_Status {
	if x != nil {
		return x.Status
	}
	return PollDeviceLoginResponse_STATUS_UNSPECIFIED
}

func (x *PollDeviceLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *PollDeviceLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *PollDeviceLoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *PollDeviceLoginResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

// Request message for the AuthService.RefreshToken rpc.
type RefreshTokenRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Optional enterprise switch: re-mint the access token scoped to this
	// enterprise instead of the session's current one. Must be an enterprise the
	// caller is a member of; empty keeps the session's existing scope.
	EnterpriseId  string `protobuf:"bytes,2,opt,name=enterprise_id,json=enterpriseId,proto3" json:"enterprise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetEnterpriseId() string {
	if x != nil {
		return x.EnterpriseId
	}
	return ""
}

// Response message for the AuthService.RefreshToken rpc.
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // rotated (same value until rotation lands in phase 6)
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// Request message for the AuthService.Logout rpc.
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // session to revoke
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Response message for the AuthService.Logout rpc.
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jennah_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_jennah_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

var File_jennah_auth_v1_auth_proto protoreflect.FileDescriptor

const file_jennah_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x19jennah/auth/v1/auth.proto\x12\x11jennahapi.auth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$gnostic/openapi/v3/annotations.proto\"^\n" +
	"\n" +
	"Membership\x12#\n" +
	"\renterprise_id\x18\x01 \x01(\tR\fenterpriseId\x12+\n" +
	"\x04role\x18\x02 \x01(\x0e2\x17.jennahapi.auth.v1.RoleR\x04role\"\x82\x03\n" +
	"\bIdentity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x03 \x01(\bR\remailVerified\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x05 \x01(\tR\apicture\x127\n" +
	"\bprovider\x18\x06 \x01(\x0e2\x1b.jennahapi.auth.v1.ProviderR\bprovider\x12F\n" +
	"\x10linked_providers\x18\a \x03(\x0e2\x1b.jennahapi.auth.v1.ProviderR\x0flinkedProviders\x120\n" +
	"\x14active_enterprise_id\x18\b \x01(\tR\x12activeEnterpriseId\x12?\n" +
	"\vmemberships\x18\t \x03(\v2\x1d.jennahapi.auth.v1.MembershipR\vmemberships\"\x84\x01\n" +
	"\vEntitlement\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12>\n" +
	"\rtrial_ends_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vtrialEndsAt\x12!\n" +
	"\ftrial_active\x18\x03 \x01(\bR\vtrialActive\"\x0f\n" +
	"\rWhoAmIRequest\"\x8b\x01\n" +
	"\x0eWhoAmIResponse\x127\n" +
	"\bidentity\x18\x01 \x01(\v2\x1b.jennahapi.auth.v1.IdentityR\bidentity\x12@\n" +
	"\ventitlement\x18\x02 \x01(\v2\x1e.jennahapi.auth.v1.EntitlementR\ventitlement\"\xf5\x01\n" +
	"\x11StartLoginRequest\x127\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1b.jennahapi.auth.v1.ProviderR\bprovider\x12>\n" +
	"\vclient_type\x18\x02 \x01(\x0e2\x1d.jennahapi.auth.v1.ClientTypeR\n" +
	"clientType\x12!\n" +
	"\fapp_redirect\x18\x03 \x01(\tR\vappRedirect\x12D\n" +
	"\rresponse_mode\x18\x04 \x01(\x0e2\x1f.jennahapi.auth.v1.ResponseModeR\fresponseMode\"O\n" +
	"\x12StartLoginResponse\x12#\n" +
	"\rauthorize_url\x18\x01 \x01(\tR\fauthorizeUrl\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\xad\x01\n" +
	"\x14CompleteLoginRequest\x127\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1b.jennahapi.auth.v1.ProviderR\bprovider\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12%\n" +
	"\x0ecallback_state\x18\x03 \x01(\tR\rcallbackState\x12!\n" +
	"\fcookie_state\x18\x04 \x01(\tR\vcookieState\"\xb4\x02\n" +
	"\x15CompleteLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12!\n" +
	"\fapp_redirect\x18\x04 \x01(\tR\vappRedirect\x127\n" +
	"\bidentity\x18\x05 \x01(\v2\x1b.jennahapi.auth.v1.IdentityR\bidentity\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12D\n" +
	"\rresponse_mode\x18\a \x01(\x0e2\x1f.jennahapi.auth.v1.ResponseModeR\fresponseMode\")\n" +
	"\x13ExchangeCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xbc\x01\n" +
	"\x14ExchangeCodeResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x12\x1e\n" +
	"\vis_new_user\x18\x05 \x01(\bR\tisNewUser\"R\n" +
	"\x17StartDeviceLoginRequest\x127\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1b.jennahapi.auth.v1.ProviderR\bprovider\"\xfa\x01\n" +
	"\x18StartDeviceLoginResponse\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_uri\x18\x03 \x01(\tR\x0fverificationUri\x12:\n" +
	"\x19verification_uri_complete\x18\x04 \x01(\tR\x17verificationUriComplete\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\x03R\binterval\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x03R\texpiresIn\"9\n" +
	"\x16PollDeviceLoginRequest\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\"\xf6\x02\n" +
	"\x17PollDeviceLoginResponse\x12I\n" +
	"\x06status\x18\x01 \x01(\x0e21.jennahapi.auth.v1.PollDeviceLoginResponse.StatusR\x06status\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x127\n" +
	"\bidentity\x18\x05 \x01(\v2\x1b.jennahapi.auth.v1.IdentityR\bidentity\"p\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_APPROVED\x10\x02\x12\x11\n" +
	"\rSTATUS_DENIED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_EXPIRED\x10\x04\"_\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12#\n" +
	"\renterprise_id\x18\x02 \x01(\tR\fenterpriseId\"}\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x10\n" +
	"\x0eLogoutResponse*N\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROVIDER_GOOGLE\x10\x01\x12\x13\n" +
	"\x0fPROVIDER_GITHUB\x10\x02*S\n" +
	"\n" +
	"ClientType\x12\x1b\n" +
	"\x17CLIENT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCLIENT_TYPE_WEB\x10\x01\x12\x13\n" +
	"\x0fCLIENT_TYPE_CLI\x10\x02*a\n" +
	"\fResponseMode\x12\x1d\n" +
	"\x19RESPONSE_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RESPONSE_MODE_FRAGMENT\x10\x01\x12\x16\n" +
	"\x12RESPONSE_MODE_CODE\x10\x02*L\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_ROOT\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x032\x9c\x06\n" +
	"\vAuthService\x12f\n" +
	"\x06WhoAmI\x12 .jennahapi.auth.v1.WhoAmIRequest\x1a!.jennahapi.auth.v1.WhoAmIResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/auth/v1/whoami\x12Y\n" +
	"\n" +
	"StartLogin\x12$.jennahapi.auth.v1.StartLoginRequest\x1a%.jennahapi.auth.v1.StartLoginResponse\x12b\n" +
	"\rCompleteLogin\x12'.jennahapi.auth.v1.CompleteLoginRequest\x1a(.jennahapi.auth.v1.CompleteLoginResponse\x12_\n" +
	"\fExchangeCode\x12&.jennahapi.auth.v1.ExchangeCodeRequest\x1a'.jennahapi.auth.v1.ExchangeCodeResponse\x12k\n" +
	"\x10StartDeviceLogin\x12*.jennahapi.auth.v1.StartDeviceLoginRequest\x1a+.jennahapi.auth.v1.StartDeviceLoginResponse\x12h\n" +
	"\x0fPollDeviceLogin\x12).jennahapi.auth.v1.PollDeviceLoginRequest\x1a*.jennahapi.auth.v1.PollDeviceLoginResponse\x12_\n" +
	"\fRefreshToken\x12&.jennahapi.auth.v1.RefreshTokenRequest\x1a'.jennahapi.auth.v1.RefreshTokenResponse\x12M\n" +
	"\x06Logout\x12 .jennahapi.auth.v1.LogoutRequest\x1a!.jennahapi.auth.v1.LogoutResponseB\xab\t\xbaG\xff\b\x12\x8b\b\n" +
	"\x14Jennah API reference\x12\xee\aJennah API is a RESTful API that can be accessed by an HTTP client such as `curl`, or any HTTP library which is part of most modern programming languages. This API reference is autogenerated from [protocol buffers](https://developers.google.com/protocol-buffers) defined in this [repository](https://github.com/alphauslabs/jennah-api), together with our supported client libraries. See the official [documentation](https://alphauslabs.github.io/docs/blueapi/overview/) for more information.\n" +
	"\n" +
	"You may encounter the following feature maturity indicators:\n" +
	"- **(WORK-IN-PROGRESS)** - Development is ongoing, don't use yet;\n" +
	"- **(BETA)** - New or experimental features, subject to changes; and\n" +
	"- **(DEPRECATED)** - Outdated or replaced features.\n" +
	"\n" +
	"Some endpoints, especially those that return lists of resources, have streaming responses; newline-separated stream of “chunks”. Each chunk is an envelope that can contain either a response message or an error. Only the last chunk will include an error, if any.2\x02v1\x1a\"\n" +
	" https://api.alphaus.cloud/m/blueBK\n" +
	"\x12Service definition\x125https://github.com/alphauslabs/blueapi/tree/main/org/Z&github.com/alphauslabs/jennah-api/authb\x06proto3"

var (
	file_jennah_auth_v1_auth_proto_rawDescOnce sync.Once
	file_jennah_auth_v1_auth_proto_rawDescData []byte
)

func file_jennah_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_jennah_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_jennah_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jennah_auth_v1_auth_proto_rawDesc), len(file_jennah_auth_v1_auth_proto_rawDesc)))
	})
	return file_jennah_auth_v1_auth_proto_rawDescData
}

var file_jennah_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_jennah_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_jennah_auth_v1_auth_proto_goTypes = []any{
	(Provider)(0),                       // 0: jennahapi.auth.v1.Provider
	(ClientType)(0),                     // 1: jennahapi.auth.v1.ClientType
	(ResponseMode)(0),                   // 2: jennahapi.auth.v1.ResponseMode
	(Role)(0),                           // 3: jennahapi.auth.v1.Role
	(PollDeviceLoginResponse_Status)(0), // 4: jennahapi.auth.v1.PollDeviceLoginResponse.Status
	(*Membership)(nil),                  // 5: jennahapi.auth.v1.Membership
	(*Identity)(nil),                    // 6: jennahapi.auth.v1.Identity
	(*Entitlement)(nil),                 // 7: jennahapi.auth.v1.Entitlement
	(*WhoAmIRequest)(nil),               // 8: jennahapi.auth.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),              // 9: jennahapi.auth.v1.WhoAmIResponse
	(*StartLoginRequest)(nil),           // 10: jennahapi.auth.v1.StartLoginRequest
	(*StartLoginResponse)(nil),          // 11: jennahapi.auth.v1.StartLoginResponse
	(*CompleteLoginRequest)(nil),        // 12: jennahapi.auth.v1.CompleteLoginRequest
	(*CompleteLoginResponse)(nil),       // 13: jennahapi.auth.v1.CompleteLoginResponse
	(*ExchangeCodeRequest)(nil),         // 14: jennahapi.auth.v1.ExchangeCodeRequest
	(*ExchangeCodeResponse)(nil),        // 15: jennahapi.auth.v1.ExchangeCodeResponse
	(*StartDeviceLoginRequest)(nil),     // 16: jennahapi.auth.v1.StartDeviceLoginRequest
	(*StartDeviceLoginResponse)(nil),    // 17: jennahapi.auth.v1.StartDeviceLoginResponse
	(*PollDeviceLoginRequest)(nil),      // 18: jennahapi.auth.v1.PollDeviceLoginRequest
	(*PollDeviceLoginResponse)(nil),     // 19: jennahapi.auth.v1.PollDeviceLoginResponse
	(*RefreshTokenRequest)(nil),         // 20: jennahapi.auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),        // 21: jennahapi.auth.v1.RefreshTokenResponse
	(*LogoutRequest)(nil),               // 22: jennahapi.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),              // 23: jennahapi.auth.v1.LogoutResponse
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
}
var file_jennah_auth_v1_auth_proto_depIdxs = []int32{
	3,  // 0: jennahapi.auth.v1.Membership.role:type_name -> jennahapi.auth.v1.Role
	0,  // 1: jennahapi.auth.v1.Identity.provider:type_name -> jennahapi.auth.v1.Provider
	0,  // 2: jennahapi.auth.v1.Identity.linked_providers:type_name -> jennahapi.auth.v1.Provider
	5,  // 3: jennahapi.auth.v1.Identity.memberships:type_name -> jennahapi.auth.v1.Membership
	24, // 4: jennahapi.auth.v1.Entitlement.trial_ends_at:type_name -> google.protobuf.Timestamp
	6,  // 5: jennahapi.auth.v1.WhoAmIResponse.identity:type_name -> jennahapi.auth.v1.Identity
	7,  // 6: jennahapi.auth.v1.WhoAmIResponse.entitlement:type_name -> jennahapi.auth.v1.Entitlement
	0,  // 7: jennahapi.auth.v1.StartLoginRequest.provider:type_name -> jennahapi.auth.v1.Provider
	1,  // 8: jennahapi.auth.v1.StartLoginRequest.client_type:type_name -> jennahapi.auth.v1.ClientType
	2,  // 9: jennahapi.auth.v1.StartLoginRequest.response_mode:type_name -> jennahapi.auth.v1.ResponseMode
	0,  // 10: jennahapi.auth.v1.CompleteLoginRequest.provider:type_name -> jennahapi.auth.v1.Provider
	6,  // 11: jennahapi.auth.v1.CompleteLoginResponse.identity:type_name -> jennahapi.auth.v1.Identity
	2,  // 12: jennahapi.auth.v1.CompleteLoginResponse.response_mode:type_name -> jennahapi.auth.v1.ResponseMode
	0,  // 13: jennahapi.auth.v1.StartDeviceLoginRequest.provider:type_name -> jennahapi.auth.v1.Provider
	4,  // 14: jennahapi.auth.v1.PollDeviceLoginResponse.status:type_name -> jennahapi.auth.v1.PollDeviceLoginResponse.Status
	6,  // 15: jennahapi.auth.v1.PollDeviceLoginResponse.identity:type_name -> jennahapi.auth.v1.Identity
	8,  // 16: jennahapi.auth.v1.AuthService.WhoAmI:input_type -> jennahapi.auth.v1.WhoAmIRequest
	10, // 17: jennahapi.auth.v1.AuthService.StartLogin:input_type -> jennahapi.auth.v1.StartLoginRequest
	12, // 18: jennahapi.auth.v1.AuthService.CompleteLogin:input_type -> jennahapi.auth.v1.CompleteLoginRequest
	14, // 19: jennahapi.auth.v1.AuthService.ExchangeCode:input_type -> jennahapi.auth.v1.ExchangeCodeRequest
	16, // 20: jennahapi.auth.v1.AuthService.StartDeviceLogin:input_type -> jennahapi.auth.v1.StartDeviceLoginRequest
	18, // 21: jennahapi.auth.v1.AuthService.PollDeviceLogin:input_type -> jennahapi.auth.v1.PollDeviceLoginRequest
	20, // 22: jennahapi.auth.v1.AuthService.RefreshToken:input_type -> jennahapi.auth.v1.RefreshTokenRequest
	22, // 23: jennahapi.auth.v1.AuthService.Logout:input_type -> jennahapi.auth.v1.LogoutRequest
	9,  // 24: jennahapi.auth.v1.AuthService.WhoAmI:output_type -> jennahapi.auth.v1.WhoAmIResponse
	11, // 25: jennahapi.auth.v1.AuthService.StartLogin:output_type -> jennahapi.auth.v1.StartLoginResponse
	13, // 26: jennahapi.auth.v1.AuthService.CompleteLogin:output_type -> jennahapi.auth.v1.CompleteLoginResponse
	15, // 27: jennahapi.auth.v1.AuthService.ExchangeCode:output_type -> jennahapi.auth.v1.ExchangeCodeResponse
	17, // 28: jennahapi.auth.v1.AuthService.StartDeviceLogin:output_type -> jennahapi.auth.v1.StartDeviceLoginResponse
	19, // 29: jennahapi.auth.v1.AuthService.PollDeviceLogin:output_type -> jennahapi.auth.v1.PollDeviceLoginResponse
	21, // 30: jennahapi.auth.v1.AuthService.RefreshToken:output_type -> jennahapi.auth.v1.RefreshTokenResponse
	23, // 31: jennahapi.auth.v1.AuthService.Logout:output_type -> jennahapi.auth.v1.LogoutResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_jennah_auth_v1_auth_proto_init() }
func file_jennah_auth_v1_auth_proto_init() {
	if File_jennah_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jennah_auth_v1_auth_proto_rawDesc), len(file_jennah_auth_v1_auth_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jennah_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_jennah_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_jennah_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_jennah_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_jennah_auth_v1_auth_proto = out.File
	file_jennah_auth_v1_auth_proto_goTypes = nil
	file_jennah_auth_v1_auth_proto_depIdxs = nil
}
